/**
 * THE LONG MERIDIAN - Configuration & Game Constants
 */

export const CONFIG = {
  VERSION: '1.0.0',
  GAME_TITLE: 'THE LONG MERIDIAN',
  SUBTITLE: 'Northern Survival Corridor',

  // World & Generation
  WORLD: {
    CHUNK_LENGTH: 80,          // Length of each procedural road chunk (meters)
    VISIBLE_CHUNKS: 5,         // Number of chunks rendered ahead/behind
    ROAD_SEGMENTS_PER_CHUNK: 20,
    BASE_ROAD_WIDTH: 24.0,     // Generous 24m highway (2 wide travel lanes + emergency shoulders)
    DESPAWN_DISTANCE: 70,      // Distance behind player to recycle chunks
    ROAD_Y: 0,
  },

  // Real-World Natural Biomes of Planet Earth: The Grand Trans-Earth Meridian Expedition
  BIOMES: {
    MEDITERRANEAN_COAST: {
      id: 'mediterranean_coast',
      sectorIndex: 0,
      name: 'Riviera dei Pini & Coste Rocciose',
      subname: 'Costa Mediterranea & Macchia Aromatica [PK 0.0 - 0.65 KM]',
      loreTitle: 'Falesie Calcaree, Pini Marittimi & Asfalto sul Mare',
      history: 'Punto di partenza della Spedizione Planetaria del Grande Meridiano. La strada costiera si snoda a picco sul mare azzurro cobalto, tra pinete marittime profumate di resina, ulivi saraceni e muretti a secco in pietra viva. La brezza salmastra rinfresca i motori, ma il calcare polveroso si deposita sui filtri dell\'aria.',
      settlementName: 'Porto San Vito & Vecchia Tonnara',
      settlementPK: 220,
      colorSky: 0x38bdf8,
      colorFog: 0x7dd3fc,
      colorGround: 0x854d0e,
      colorRoad: 0x334155,
      fogDensity: 0.012,
      ambientIntensity: 0.62,
      sunIntensity: 1.25,
      sunColor: 0xfffbeb,
      roadRoughness: 0.35,
      tractionFactor: 1.0,
      weatherTypes: ['clear', 'sea_breeze', 'heatwave'],
      hazardFrequency: 0.3,
      musicMood: 'mediterranean_breeze',
      environmentalThreat: 'Banchine strette a strapiombo sulle scogliere e polvere calcarea bianca scivolosa nelle curve veloci.',
      primaryExport: ['refined_fuel', 'water_purified', 'toolkit'],
      criticalNeed: ['spare_tire', 'scrap_metal', 'engine_oil'],
      recommendedGear: 'Assetto stradale preciso, filtro aria a bagno d\'olio per la polvere calcarea'
    },
    TEMPERATE_FOREST: {
      id: 'temperate_forest',
      sectorIndex: 1,
      name: 'Valli Appenniniche & Querce Frondose',
      subname: 'Foresta Temperata di Latifoglie & Fiumi [PK 0.65 - 1.30 KM]',
      loreTitle: 'Boschi di Querce e Faggi, Ponti in Pietra & Valli Nebbiose',
      history: 'Il convoglio penetra nella grande foresta temperata di fondovalle. Querce secolari e faggi creano una galleria verde d\'ombra screziata dal sole. I corsi d\'acqua sono scavalcati da storici ponti ad arco in pietra d\'arenaria. Al mattino la nebbia fluviale ristagna nei fondovalle rendendo l\'asfalto umido e viscido.',
      settlementName: 'Mulino di Valbruna & Segheria Idraulica',
      settlementPK: 870,
      colorSky: 0x0f172a,
      colorFog: 0x164e63,
      colorGround: 0x14532d,
      colorRoad: 0x1e293b,
      fogDensity: 0.022,
      ambientIntensity: 0.48,
      sunIntensity: 0.95,
      sunColor: 0xfef08a,
      roadRoughness: 0.5,
      tractionFactor: 0.88,
      weatherTypes: ['heavy_mist', 'rain', 'overcast'],
      hazardFrequency: 0.4,
      musicMood: 'dark_forest',
      environmentalThreat: 'Fogliame fradicio sul manto stradale che riduce l\'aderenza in frenata; fitti banchi di nebbia fluviale.',
      primaryExport: ['cured_timber', 'first_aid_bandage', 'water_purified'],
      criticalNeed: ['fuel_canister', 'spark_plugs', 'scrap_metal'],
      recommendedGear: 'Tergicristalli efficienti, fari fendinebbia gialli vintage'
    },
    ARID_DESERT: {
      id: 'arid_desert',
      sectorIndex: 2,
      name: 'Grande Erg Sahariano & Oasi di Fuoco',
      subname: 'Deserto Arido, Dune Ondulate & Piste Reg [PK 1.30 - 1.95 KM]',
      loreTitle: 'Oceano di Sabbia Dorata, Tempeste di Polvere & Calore +45°C',
      history: 'La transizione nel deserto più vasto e implacabile del pianeta. Una distesa infinita di dune di sabbia finissima, lastroni di roccia erosa dal vento (reg) e specchi d\'acqua salmastra nelle oasi carovaniere. Il termometro tocca i 46°C: la temperatura dell\'acqua motore schizza alle stelle se non si modula il gas.',
      settlementName: 'Oasi di El-Kantara & Forte Carovaniero',
      settlementPK: 1520,
      colorSky: 0x78350f,
      colorFog: 0xb45309,
      colorGround: 0xd97706,
      colorRoad: 0x92400e,
      fogDensity: 0.015,
      ambientIntensity: 0.75,
      sunIntensity: 1.45,
      sunColor: 0xffedd5,
      roadRoughness: 0.65,
      tractionFactor: 0.72,
      weatherTypes: ['heatwave', 'sandstorm', 'clear'],
      hazardFrequency: 0.5,
      heatDanger: true,
      musicMood: 'desert_wind',
      environmentalThreat: 'Calore estremo che minaccia di far bollire il radiatore; dune ventate mobili che possono insabbiare le ruote.',
      primaryExport: ['waterproofing_wax', 'refined_fuel', 'engine_oil'],
      criticalNeed: ['water_bottle', 'water_purified', 'spare_tire'],
      recommendedGear: '4WD o marcia corta Primina per disincagliarsi dalla sabbia, ventola radiatore sempre attiva'
    },
    SAVANNA_STEPPE: {
      id: 'savanna_steppe',
      sectorIndex: 3,
      name: 'Savana del Serengeti & Terra Rossa',
      subname: 'Prateria dell\'Acacia & Piste Lateritiche [PK 1.95 - 2.60 KM]',
      loreTitle: 'Piste di Terra Rossa, Baobab Millenari & Vaste Praterie Dorate',
      history: 'L\'altopiano della savana africana: distese d\'erba bionda punteggiate da acacie ad ombrello e imponenti baobab che sfidano i secoli. La carreggiata è una pista di terra battuta rossa lateritica, con corrugazioni e canaloni d\'acqua asciutti scavati dalle piogge passate.',
      settlementName: 'Stazione Ranger della Piana d\'Oro',
      settlementPK: 2170,
      colorSky: 0x451a03,
      colorFog: 0x9a3412,
      colorGround: 0xb91c1c,
      colorRoad: 0x7f1d1d,
      fogDensity: 0.016,
      ambientIntensity: 0.65,
      sunIntensity: 1.25,
      sunColor: 0xfed7aa,
      roadRoughness: 0.6,
      tractionFactor: 0.84,
      weatherTypes: ['clear', 'overcast', 'sandstorm'],
      hazardFrequency: 0.45,
      musicMood: 'industrial_drone',
      environmentalThreat: 'Fondo stradale a lamiera ondulata che martella le boccole delle sospensioni e buche di fango secco a sorpresa.',
      primaryExport: ['reinforced_coil', 'armor_plate', 'canned_stew'],
      criticalNeed: ['first_aid_bandage', 'toolkit', 'refined_fuel'],
      recommendedGear: 'Ammortizzatori a doppio effetto per assorbire le ondulazioni della pista rossa'
    },
    TROPICAL_RAINFOREST: {
      id: 'tropical_rainforest',
      sectorIndex: 4,
      name: 'Giungla di Rio Verde & Monsoni Equatoriali',
      subname: 'Foresta Pluviale Equatoriale & Fango Viscido [PK 2.60 - 3.25 KM]',
      loreTitle: 'Vegetazione Monumentale, Diluvi Monsonici & Argilla Liquida',
      history: 'La fitta volta della foresta pluviale equatoriale, dove la luce solare filtra appena attraverso le chiome di ficus giganti e felci arboree. L\'umidità sfiora il 98% e acquazzoni monsonici torrenziali trasformano la pista in un letto di argilla liquida e pozze d\'acqua che mettono a dura prova l\'impianto elettrico.',
      settlementName: 'Avamposto Botanico Rio Verde & Scalo Fluviale',
      settlementPK: 2820,
      colorSky: 0x064e3b,
      colorFog: 0x022c22,
      colorGround: 0x052e16,
      colorRoad: 0x14532d,
      fogDensity: 0.028,
      ambientIntensity: 0.4,
      sunIntensity: 0.8,
      sunColor: 0x6ee7b7,
      roadRoughness: 0.75,
      tractionFactor: 0.62,
      weatherTypes: ['tropical_monsoon', 'torrential_rain', 'dense_fog'],
      hazardFrequency: 0.55,
      musicMood: 'aquatic_melancholy',
      environmentalThreat: 'Aquaplaning severo e fanghiglia argillosa a bassissima trazione; rischio di bagnare spinterogeno e candele nei guadi.',
      primaryExport: ['antiseptic_resin', 'waterproofing_wax', 'peat_filter'],
      criticalNeed: ['electronics', 'spare_tire', 'engine_oil'],
      recommendedGear: 'Snorkel per la presa d\'aria motore, trazione integrale 4WD inserita, cera siliconica sui cavi'
    },
    ALPINE_PEAKS: {
      id: 'alpine_peaks',
      sectorIndex: 5,
      name: 'Valico delle Aquile & Vette Alpine',
      subname: 'Massiccio di Granito & Tornanti a 2.450m [PK 3.25 - 3.90 KM]',
      loreTitle: 'Falesie di Roccia Nuda, Tornanti a Gomito & Pendenze del 14%',
      history: 'La scalata del tetto del mondo continentale. Il tracciato si inerpica su tornanti scavati nella viva roccia di granito, con cascate di disgelo e strapiombi vertiginosi. L\'aria rarefatta d\'alta quota toglie fiato e potenza ai carburatori, mentre le discese prolungate surriscaldano i freni a tamburo.',
      settlementName: 'Rifugio Valico delle Aquile (Passo Alpino 2.450m)',
      settlementPK: 3470,
      colorSky: 0x1e293b,
      colorFog: 0x334155,
      colorGround: 0x475569,
      colorRoad: 0x1e293b,
      fogDensity: 0.016,
      ambientIntensity: 0.55,
      sunIntensity: 1.3,
      sunColor: 0xfff7ed,
      roadRoughness: 0.85,
      tractionFactor: 0.82,
      weatherTypes: ['mountain_gale', 'freezing_rain', 'clear'],
      hazardFrequency: 0.5,
      musicMood: 'anomalous_pulse',
      environmentalThreat: 'Pietrisco di franamento tagliente in curva e fading termico dei freni nelle discese prolungate.',
      primaryExport: ['tungsten_drill_bit', 'reinforced_coil', 'armor_plate'],
      criticalNeed: ['fuel_canister', 'refined_fuel', 'canned_stew'],
      recommendedGear: 'Freno motore in marcia bassa, pastiglie e ganasce freno rinforzate, paramassi sottoscocca'
    },
    BOREAL_TAIGA: {
      id: 'boreal_taiga',
      sectorIndex: 6,
      name: 'Taiga Siberiana & Foreste di Conifere',
      subname: 'Abeti Innevati, Ponti di Tronchi & Permafrost [PK 3.90 - 4.55 KM]',
      loreTitle: 'L\'Immenso Mare Verde delle Conifere Subartiche & Fiumi Gelati',
      history: 'La sterminata taiga boreale: milioni di abeti e picea che si estendono a perdita d\'occhio sotto cieli di piombo freddo. La strada attraversa fiumi ghiacciati con passerelle e cordoni di tronchi. Il suolo nasconde il permafrost e a motore spento la temperatura scende rapidamente sottozero.',
      settlementName: 'Stazione Forestale Taiga Nord & Scalo Zattere',
      settlementPK: 4120,
      colorSky: 0x0f172a,
      colorFog: 0x1e293b,
      colorGround: 0x1e293b,
      colorRoad: 0x334155,
      fogDensity: 0.024,
      ambientIntensity: 0.42,
      sunIntensity: 0.65,
      sunColor: 0xbfdbfe,
      roadRoughness: 0.65,
      tractionFactor: 0.68,
      weatherTypes: ['heavy_mist', 'blizzard', 'overcast'],
      hazardFrequency: 0.55,
      coldDanger: true,
      musicMood: 'cold_isolation',
      environmentalThreat: 'Freddo rigido a -10°C che congela l\'umidità nei condotti carburante; lastroni di ghiaccio nascosti sotto aghi di pino.',
      primaryExport: ['cured_timber', 'cryo_coolant', 'toolkit'],
      criticalNeed: ['graphene_battery', 'refined_fuel', 'water_purified'],
      recommendedGear: 'Candele calde per basse temperature, additivo anticongelante nel serbatoio'
    },
    POLAR_TUNDRA: {
      id: 'polar_tundra',
      sectorIndex: 7,
      name: 'Calotta Polare & Oceano Artico',
      subname: 'Banchisa Glaciale, Aurore Boreali & 80° Parallelo [PK 4.55 - 5.20+ KM]',
      loreTitle: 'Il Traguardo della Notte Polare, Vetrone Vivo & Aurore Cosmiche',
      history: 'Il punto più a nord dell\'intero globo terrestre: la banchisa polare affacciata sull\'Oceano Artico all\'80° Parallelo. Sotto il cielo nero illuminato da aurore boreali smeraldo e violette, la strada è una lastra di verglas e ghiaccio compatto. Il termometro tocca -46°C: solo chi possiede coraggio e un veicolo leggendario può raggiungere la base scientifica finale.',
      settlementName: 'Base Scientifica Globale 80° Parallelo',
      settlementPK: 4770,
      colorSky: 0x020617,
      colorFog: 0x0f172a,
      colorGround: 0x1e293b,
      colorRoad: 0x38bdf8,
      fogDensity: 0.025,
      ambientIntensity: 0.35,
      sunIntensity: 0.45,
      sunColor: 0xa5f3fc,
      roadRoughness: 0.5,
      tractionFactor: 0.38,
      weatherTypes: ['blizzard', 'aurora_static', 'freezing_rain'],
      hazardFrequency: 0.65,
      coldDanger: true,
      musicMood: 'cold_isolation',
      environmentalThreat: 'Gelo polare estremo (-45°C) e lastroni di ghiaccio vivo: trazione ridotta al 38% e rischio di congelamento blocco motore.',
      primaryExport: ['cryo_coolant', 'thermal_lining', 'electronics'],
      criticalNeed: ['spare_tire', 'fuel_canister', 'engine_oil'],
      recommendedGear: 'Glicole criogenico antigelo, gomme chiodate, fari ausiliari di profondità per la notte polare'
    }
  },

  // Major Settlements and Trade Hubs along the Trans-Earth Meridian
  SETTLEMENTS: {
    san_vito_harbor: {
      id: 'san_vito_harbor',
      biomeId: 'mediterranean_coast',
      pk: 220,
      name: 'Porto San Vito & Vecchia Tonnara',
      faction: 'Consorzio Marinaro e Meccanici della Riviera',
      population: 140,
      icon: '⚓',
      description: 'Borgo marinaro fortificato incastonato tra le scogliere calcaree e le pinete costiere. I pescatori e i mastri d\'ascia scambiano carburante filtrato, acqua di sorgente e arnesi d\'officina in cambio di ricambi metallici.',
      tacticalAdvice: 'Fai il pieno di carburante e acquista chiavi inglesi: lungo la costa l\'asfalto è scorrevole, ma l\'avvicinamento all\'entroterra richiederà attrezzi solidi.',
      buysMultiplier: 2.5,
      sellsDiscount: 0.7
    },
    valbruna_mill: {
      id: 'valbruna_mill',
      biomeId: 'temperate_forest',
      pk: 870,
      name: 'Mulino di Valbruna & Segheria Idraulica',
      faction: 'Gilda Forestale & Guardiacaccia Appenninici',
      population: 95,
      icon: '🪵',
      description: 'Storico insediamento sul fiume azionato da due grandi ruote idrauliche. I boscaioli stagionano legname duro di faggio e quercia ed estraggono resine lenitive per le bende mediche.',
      tacticalAdvice: 'Acquista travi di legno stagionato per rinforzare il pianale: ti serviranno per affrontare il deserto e la savana.',
      buysMultiplier: 2.5,
      sellsDiscount: 0.7
    },
    elkantara_oasis: {
      id: 'elkantara_oasis',
      biomeId: 'arid_desert',
      pk: 1520,
      name: 'Oasi di El-Kantara & Forte Carovaniero',
      faction: 'Carovanieri Nomadi Tuareg & Meccanici del Deserto',
      population: 120,
      icon: '🌴',
      description: 'Un\'oasi millenaria circondata da palme da dattero e mura d\'argilla rinforzata. I meccanici locali sono leggendari per la capacità di riparare qualsiasi radiatore con paste sigillanti idrorepellenti.',
      tacticalAdvice: 'Nel deserto l\'acqua pura vale oro. Compra cera protettiva e taniche d\'acqua prima di affrontare le tempeste di sabbia.',
      buysMultiplier: 2.5,
      sellsDiscount: 0.7
    },
    serengeti_outpost: {
      id: 'serengeti_outpost',
      biomeId: 'savanna_steppe',
      pk: 2170,
      name: 'Stazione Ranger della Piana d\'Oro',
      faction: 'Ranger della Riserva Naturale & Trasportatori del Bush',
      population: 75,
      icon: '🦁',
      description: 'Bivacco fortificato sotto un gigantesco baobab centenario. I guardaparco forgiano piastre corazzate e balestre rinforzate in grado di resistere ai colpi delle corrugazioni della pista lateritica.',
      tacticalAdvice: 'Installa balestre da carico pesanti per non spanciare sui dislivelli della savana. I ranger pagheranno caro bende e medicinali.',
      buysMultiplier: 2.5,
      sellsDiscount: 0.7
    },
    rioverde_station: {
      id: 'rioverde_station',
      biomeId: 'tropical_rainforest',
      pk: 2820,
      name: 'Avamposto Botanico Rio Verde & Scalo Fluviale',
      faction: 'Esploratori Idrologi & Comunità Indigena Fluviale',
      population: 68,
      icon: '🌿',
      description: 'Villaggio su palafitte di teak affacciato sul grande fiume equatoriale. I biologi distillano cere idrofobiche per isolare gli spinterogeni ed estraggono filtri a torba ad altissima capacità.',
      tacticalAdvice: 'I monsoni equatoriali allagano la carreggiata. Assicurati di avere la trazione integrale funzionante e pneumatici a tasselli profondi.',
      buysMultiplier: 2.5,
      sellsDiscount: 0.7
    },
    valico_aquile: {
      id: 'valico_aquile',
      biomeId: 'alpine_peaks',
      pk: 3470,
      name: 'Rifugio Valico delle Aquile (Passo Alpino 2.450m)',
      faction: 'Soccorso Alpino & Cantonieri dell\'Alta Quota',
      population: 52,
      icon: '🏔️',
      description: 'Rifugio in pietra granitica incastonato sulla forcella a 2.450 metri di quota. I cantonieri gestiscono frese sgombraneve e forgiano punte al tungsteno e balestre rinforzate per arrampicarsi sui ripidi tornanti.',
      tacticalAdvice: 'Le pendenze del 14% richiedono una prima marcia corta. Non surriscaldare i freni: usa sempre il freno motore nelle discese.',
      buysMultiplier: 2.5,
      sellsDiscount: 0.7
    },
    taiga_nord: {
      id: 'taiga_nord',
      biomeId: 'boreal_taiga',
      pk: 4120,
      name: 'Stazione Forestale Taiga Nord & Scalo Zattere',
      faction: 'Taglialegna Siberiani & Tecnici della Transcontinentale',
      population: 80,
      icon: '🌲',
      description: 'Avamposto tra le conifere innevate della taiga siberiana. Forniscono fluido criogenico antigelo e pannelli termoisolanti per impedire che l\'olio motore diventi solido durante le soste.',
      tacticalAdvice: 'Il freddo umido a -10°C gela i carburatori. Monta isolamento termico nel vano motore e fai scorta di antigelo.',
      buysMultiplier: 2.5,
      sellsDiscount: 0.7
    },
    polar_base_80: {
      id: 'polar_base_80',
      biomeId: 'polar_tundra',
      pk: 4770,
      name: 'Base Scientifica Globale 80° Parallelo',
      faction: 'Consorzio Scientifico Internazionale dell\'Oceano Polare',
      population: 45,
      icon: '❄️',
      description: 'Il capolinea assoluto del Grande Meridiano sulle sponde ghiacciate dell\'Oceano Glaciale Artico. Costruito su piloni idraulici riscaldati, è il cuore della ricerca sismica e planetaria.',
      tacticalAdvice: 'A -45°C il ghiaccio vivo offre aderenza minima. Guida con delicatezza estrema e goditi lo spettacolo dell\'aurora boreale sul traguardo!',
      buysMultiplier: 2.5,
      sellsDiscount: 0.7
    },

    // Legacy Aliases for backwards-compatibility
    fox_junction: { id: 'fox_junction', biomeId: 'mediterranean_coast', pk: 220, name: 'Porto San Vito (Ex Fox)', icon: '⚓', buysMultiplier: 2.5, sellsDiscount: 0.7 },
    yukon_crossing: { id: 'yukon_crossing', biomeId: 'temperate_forest', pk: 870, name: 'Mulino di Valbruna (Ex Yukon)', icon: '🪵', buysMultiplier: 2.5, sellsDiscount: 0.7 },
    coldfoot_camp: { id: 'coldfoot_camp', biomeId: 'arid_desert', pk: 1520, name: 'Oasi di El-Kantara (Ex Coldfoot)', icon: '🌴', buysMultiplier: 2.5, sellsDiscount: 0.7 },
    chandalar_shelf: { id: 'chandalar_shelf', biomeId: 'savanna_steppe', pk: 2170, name: 'Piana d\'Oro (Ex Chandalar)', icon: '🦁', buysMultiplier: 2.5, sellsDiscount: 0.7 },
    atigun_camp: { id: 'atigun_camp', biomeId: 'alpine_peaks', pk: 3470, name: 'Valico delle Aquile (Ex Atigun)', icon: '🏔️', buysMultiplier: 2.5, sellsDiscount: 0.7 },
    deadhorse_terminal: { id: 'deadhorse_terminal', biomeId: 'polar_tundra', pk: 4770, name: 'Base 80° Parallelo (Ex Deadhorse)', icon: '❄️', buysMultiplier: 2.5, sellsDiscount: 0.7 }
  },

  // Surface materials details
  SURFACES: {
    ASPHALT: { name: 'Asfalto Panoramico', friction: 1.0, wearMultiplier: 1.0, sound: 'asphalt' },
    DIRT: { name: 'Fango Argilloso Temperato', friction: 0.75, wearMultiplier: 1.4, sound: 'dirt' },
    GRAVEL: { name: 'Ghiaia e Detriti', friction: 0.8, wearMultiplier: 1.3, sound: 'gravel' },
    ICE: { name: 'Ghiaccio Vivo & Verglas', friction: 0.35, wearMultiplier: 0.8, sound: 'ice' },
    SLUDGE: { name: 'Argilla Liquida Equatoriale', friction: 0.52, wearMultiplier: 2.0, sound: 'sludge' },
    STEEL_BRIDGE: { name: 'Grigliato d\'Acciaio & Ponti', friction: 0.9, wearMultiplier: 1.1, sound: 'metal' },
    SAND: { name: 'Sabbia Cedevole delle Dune', friction: 0.58, wearMultiplier: 1.8, sound: 'dirt' },
    RED_DIRT: { name: 'Terra Rossa di Savana (Laterite)', friction: 0.82, wearMultiplier: 1.2, sound: 'dirt' },
    ALPINE_ROCK: { name: 'Pietrisco e Granito Alpino', friction: 0.75, wearMultiplier: 1.5, sound: 'gravel' }
  },

  // Real European Classic Vehicles Catalog (1960s - 2000s)
  DEFAULT_VEHICLE_ID: 'panda_4x4',

  VEHICLES_CATALOG: {
    panda_4x4: {
      id: 'panda_4x4',
      name: 'Panda 4x4 Steyr-Puch',
      maker: 'Fiat',
      year: 1983,
      country: 'Italia / Austria',
      flag: '🇮🇹',
      category: 'Utilitaria Integrale Leggera',
      engine: '965cc A112 Asta e Bilancieri',
      cylinders: 4,
      displacementCc: 965,
      powerHp: 48,
      torqueNm: 74,
      redlineRpm: 6000,
      idleRpm: 850,
      topSpeedKmh: 135,
      weightKg: 780,
      drivetrain: '4WD_MANUAL',
      drivetrainBadge: '4WD STEYR INSERIBILE',
      hasTurbo: false,
      turboBoostMaxBar: 0,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 35,
      fuelConsumptionRate: 0.024,
      trunkCapacityKg: 85,
      tractionBonus: 1.15,
      handling: {
        agility: 1.25,
        oversteerTendency: 0.1,
        stability: 0.85,
        brakeForce: 30.0,
        groundClearance: 0.19,
        bodyRollFactor: 0.28
      },
      dashTheme: {
        style: 'veglia_minimal',
        speedoMax: 160,
        redlineRpm: 6000,
        clusterName: 'VEGLIA BORLETTI PANDA',
        dialBg: '#12161a',
        tickColor: '#94a3b8',
        needleColor: '#f97316',
        accentColor: '#22c55e',
        hasGlowPlug: false,
        hasTurboGauge: false
      },
      soundProfile: {
        baseFreq: 42,
        timbre: 'raspy_4cyl',
        cylinders: 4,
        turboWhistle: 0.0,
        dieselKnock: 0.0
      },
      description: 'Progettata da Giorgetto Giugiaro con trazione integrale sviluppata da Steyr-Puch a Graz. Pesa appena 780 kg e dispone della leggendaria "primina" ultra-corta che le permette di arrampicarsi su pendenze del 50%.',
      tacticalDaltonAdvice: 'La leggerezza eccezionale le impedisce di sprofondare nel fango muskeg del Koyukuk e sulla neve fresca. Manca di potenza sulla salita dell\'Atigun Pass a pieno carico.',
      tier: 1,
      unlockType: 'default',
      discoveryPK: 0,
      discoveryLocation: 'Livengood Staging Post [MP 0]',
      restorationCost: {},
      restorationStory: 'La tua fidata compagna di partenza: leggera, agile e dotata della leggendaria primina Steyr-Puch.'
    },

    delta_integrale: {
      id: 'delta_integrale',
      name: 'Delta HF Integrale Evoluzione',
      maker: 'Lancia',
      year: 1991,
      country: 'Italia',
      flag: '🇮🇹',
      category: 'Rally Special Gr.A WRC',
      engine: '2.0L 16V Turbo Garrett T3 Intercooler',
      cylinders: 4,
      displacementCc: 1995,
      powerHp: 210,
      torqueNm: 300,
      redlineRpm: 6800,
      idleRpm: 950,
      topSpeedKmh: 220,
      weightKg: 1300,
      drivetrain: 'AWD_TORSEN',
      drivetrainBadge: 'TORSEN AWD 47:53',
      hasTurbo: true,
      turboBoostMaxBar: 1.4,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 57,
      fuelConsumptionRate: 0.048,
      trunkCapacityKg: 95,
      tractionBonus: 1.35,
      handling: {
        agility: 1.2,
        oversteerTendency: 0.25,
        stability: 1.15,
        brakeForce: 38.0,
        groundClearance: 0.14,
        bodyRollFactor: 0.16
      },
      dashTheme: {
        style: 'veglia_rally_yellow',
        speedoMax: 260,
        redlineRpm: 6800,
        clusterName: 'VEGLIA COMPETIZIONE CORSE',
        dialBg: '#0f1115',
        tickColor: '#eab308',
        needleColor: '#ef4444',
        accentColor: '#eab308',
        hasGlowPlug: false,
        hasTurboGauge: true
      },
      soundProfile: {
        baseFreq: 39,
        timbre: 'rally_turbo_4cyl',
        cylinders: 4,
        turboWhistle: 0.85,
        dieselKnock: 0.0
      },
      description: 'Regina incontrastata di 6 titoli mondiali rally costruttori consecutivi. Trazione integrale permanente con differenziale epicicloidale e giunto Ferguson centrale abbinato al differenziale Torsen posteriore.',
      tacticalDaltonAdvice: 'Velocità e tenuta laterale devastanti sui tratti veloci di ghiaia battuta. Fai attenzione al consumo carburante elevato e all\'entrata repentina della turbina Garrett sui fondi ghiacciati.',
      tier: 4,
      unlockType: 'barn_find',
      discoveryPK: 6500,
      discoveryLocation: 'Hangar Spedizione Polare Deadhorse [MP 414]',
      restorationCost: { scrap_metal: 85, electronics: 30, armor_plate: 1, graphene_battery: 1 },
      restorationStory: 'La leggenda dei 6 titoli mondiali rally costruttori consecutivi. Nascosta nell\'hangar terminale di Deadhorse sul Mar Glaciale Artico. Trasferisce 210 CV alle 4 ruote con un equilibrio sovrannaturale.'
    },

    mercedes_w123: {
      id: 'mercedes_w123',
      name: 'W123 300TD Turbodiesel Wagon',
      maker: 'Mercedes-Benz',
      year: 1980,
      country: 'Germania',
      flag: '🇩🇪',
      category: 'Station Wagon Indistruttibile',
      engine: '3.0L OM617 5 Cilindri Turbodiesel',
      cylinders: 5,
      displacementCc: 2998,
      powerHp: 125,
      torqueNm: 250,
      redlineRpm: 4600,
      idleRpm: 750,
      topSpeedKmh: 170,
      weightKg: 1620,
      drivetrain: 'RWD',
      drivetrainBadge: 'RWD DIFFERENZIALE POST.',
      hasTurbo: true,
      turboBoostMaxBar: 0.8,
      isDiesel: true,
      fuelType: 'gasolio',
      fuelTankL: 72,
      fuelConsumptionRate: 0.032,
      trunkCapacityKg: 165,
      tractionBonus: 0.88,
      handling: {
        agility: 0.85,
        oversteerTendency: 0.45,
        stability: 1.1,
        brakeForce: 34.0,
        groundClearance: 0.17,
        bodyRollFactor: 0.32
      },
      dashTheme: {
        style: 'vdo_mercedes_classic',
        speedoMax: 200,
        redlineRpm: 4600,
        clusterName: 'VDO STUTTGART CLASSIC',
        dialBg: '#131518',
        tickColor: '#e2e8f0',
        needleColor: '#fb923c',
        accentColor: '#f59e0b',
        hasGlowPlug: true,
        hasTurboGauge: true
      },
      soundProfile: {
        baseFreq: 33,
        timbre: 'om617_diesel_5cyl',
        cylinders: 5,
        turboWhistle: 0.4,
        dieselKnock: 0.75
      },
      description: 'L\'apice della longevità ingegneristica tedesca: il 5 cilindri OM617 turbodiesel con pompa iniezione Bosch meccanica è capace di superare un milione di chilometri senza revisioni anche con carburanti impuri.',
      tacticalDaltonAdvice: 'Il bagagliaio immenso (165 kg) e il grande serbatoio consentono lunghissime tratte senza rifornimenti. Trazione posteriore: richiede cautela sulle salite innevate dell\'Atigun Pass.',
      tier: 2,
      unlockType: 'barn_find',
      discoveryPK: 850,
      discoveryLocation: 'Scalo Chiatte del Fiume Yukon [MP 56]',
      restorationCost: { scrap_metal: 35, engine_oil: 1, cured_timber: 2 },
      restorationStory: 'Portata in Alaska da un appaltatore della Alyeska Pipeline nel 1980. Il 5 cilindri turbodiesel OM617 da un milione di chilometri è intorpidito dal gelo; con olio fresco e puntelli in legno torna a marciare.'
    },

    mercedes_gwagen: {
      id: 'mercedes_gwagen',
      name: 'G-Klasse W460 280 GE',
      maker: 'Mercedes-Benz',
      year: 1979,
      country: 'Germania / Austria',
      flag: '🇩🇪',
      category: 'Fuoristrada Militare Longheroni',
      engine: '2.8L M110 DOHC 6 Cilindri in linea',
      cylinders: 6,
      displacementCc: 2746,
      powerHp: 156,
      torqueNm: 226,
      redlineRpm: 6000,
      idleRpm: 800,
      topSpeedKmh: 155,
      weightKg: 1980,
      drivetrain: '4WD_MANUAL',
      drivetrainBadge: '3x DIFF LOCK MECCANICO',
      hasTurbo: false,
      turboBoostMaxBar: 0,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 68,
      fuelConsumptionRate: 0.042,
      trunkCapacityKg: 150,
      tractionBonus: 1.3,
      handling: {
        agility: 0.78,
        oversteerTendency: 0.2,
        stability: 1.05,
        brakeForce: 33.0,
        groundClearance: 0.23,
        bodyRollFactor: 0.35
      },
      dashTheme: {
        style: 'vdo_mercedes_military',
        speedoMax: 200,
        redlineRpm: 6000,
        clusterName: 'VDO OFF-ROAD INSTRUMENTS',
        dialBg: '#111417',
        tickColor: '#cbd5e1',
        needleColor: '#ef4444',
        accentColor: '#3b82f6',
        hasGlowPlug: false,
        hasTurboGauge: false
      },
      soundProfile: {
        baseFreq: 36,
        timbre: 'm110_inline6',
        cylinders: 6,
        turboWhistle: 0.0,
        dieselKnock: 0.0
      },
      description: 'Sviluppato per specifiche militari con telaio a longheroni e ponti rigidi guidati da bracci longitudinali. Equipaggiato con tre blocchi meccanici al 100% per i differenziali anteriore, centrale e posteriore.',
      tacticalDaltonAdvice: 'Arrampica su pietraie franose e tronchi con disinvoltura assoluta. Il peso di quasi due tonnellate penalizza i consumi e richiede frenate anticipate nelle discese viscide.',
      tier: 3,
      unlockType: 'barn_find',
      discoveryPK: 5000,
      discoveryLocation: 'Cava Frantumatori di Atigun Pass [MP 290]',
      restorationCost: { scrap_metal: 65, electronics: 20, reinforced_coil: 1 },
      restorationStory: 'Veicolo di soccorso alpino del Dipartimento Trasporti dell\'Alaska. I tre blocchi meccanici al 100% permettono di scalare le rampe del 12% dell\'Atigun Pass non appena montata una molla rinforzata.'
    },

    defender_110: {
      id: 'defender_110',
      name: 'Defender 110 200Tdi',
      maker: 'Land Rover',
      year: 1990,
      country: 'Regno Unito',
      flag: '🇬🇧',
      category: 'Spedizione Overland Artica',
      engine: '2.5L 200Tdi Turbodiesel Iniezione Diretta',
      cylinders: 4,
      displacementCc: 2495,
      powerHp: 111,
      torqueNm: 264,
      redlineRpm: 4400,
      idleRpm: 750,
      topSpeedKmh: 130,
      weightKg: 2050,
      drivetrain: '4WD_MANUAL',
      drivetrainBadge: 'PERMANENT 4WD + DIFF-LOCK',
      hasTurbo: true,
      turboBoostMaxBar: 0.9,
      isDiesel: true,
      fuelType: 'gasolio',
      fuelTankL: 80,
      fuelConsumptionRate: 0.034,
      trunkCapacityKg: 180,
      tractionBonus: 1.32,
      handling: {
        agility: 0.72,
        oversteerTendency: 0.15,
        stability: 1.0,
        brakeForce: 32.0,
        groundClearance: 0.25,
        bodyRollFactor: 0.38
      },
      dashTheme: {
        style: 'lucas_smiths_offroad',
        speedoMax: 150,
        redlineRpm: 4500,
        clusterName: 'SMITHS EXPEDITION GAUGES',
        dialBg: '#151914',
        tickColor: '#86efac',
        needleColor: '#22c55e',
        accentColor: '#16a34a',
        hasGlowPlug: true,
        hasTurboGauge: true
      },
      soundProfile: {
        baseFreq: 31,
        timbre: 'landrover_diesel_tdi',
        cylinders: 4,
        turboWhistle: 0.45,
        dieselKnock: 0.8
      },
      description: 'Icona dell\'esplorazione globale: carrozzeria in alluminio Birmabright resistente alla ruggine, snorkel di aspirazione montato sul montante A e riduttore transfer case LT230 con blocco centrale.',
      tacticalDaltonAdvice: 'Massima capacità di carico del corridoio (180 kg) e resistenza insuperabile all\'acqua e ai guadi. Sterzo pesante e andatura lenta ma inarrestabile.',
      tier: 3,
      unlockType: 'barn_find',
      discoveryPK: 4200,
      discoveryLocation: 'Staging Depot Minatori di Wiseman [MP 265]',
      restorationCost: { scrap_metal: 60, cured_timber: 3, toolkit: 1, spare_tire: 1 },
      restorationStory: 'Veterana della Royal Geographical Society abbandonata dopo un crollo sulla pista. La carrozzeria in alluminio Birmabright non ha un filo di ruggine; 180 kg di portata e riduttore con blocco differenziale.'
    },

    volvo_245: {
      id: 'volvo_245',
      name: '245 Polar Estate B230',
      maker: 'Volvo',
      year: 1988,
      country: 'Svezia',
      flag: '🇸🇪',
      category: 'Wagon Artica di Sicurezza',
      engine: '2.3L B230 "Redblock" Iniezione LH-Jetronic',
      cylinders: 4,
      displacementCc: 2316,
      powerHp: 115,
      torqueNm: 185,
      redlineRpm: 6000,
      idleRpm: 800,
      topSpeedKmh: 175,
      weightKg: 1390,
      drivetrain: 'RWD',
      drivetrainBadge: 'RWD PONTE RIGIDO DANA 30',
      hasTurbo: false,
      turboBoostMaxBar: 0,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 60,
      fuelConsumptionRate: 0.031,
      trunkCapacityKg: 150,
      tractionBonus: 0.94,
      handling: {
        agility: 0.95,
        oversteerTendency: 0.4,
        stability: 1.2,
        brakeForce: 36.0,
        groundClearance: 0.17,
        bodyRollFactor: 0.22
      },
      dashTheme: {
        style: 'yazaki_volvo_nordic',
        speedoMax: 200,
        redlineRpm: 6000,
        clusterName: 'YAZAKI GÖTEBORG INSTRUMENTS',
        dialBg: '#12171c',
        tickColor: '#93c5fd',
        needleColor: '#38bdf8',
        accentColor: '#0284c7',
        hasGlowPlug: false,
        hasTurboGauge: false
      },
      soundProfile: {
        baseFreq: 37,
        timbre: 'volvo_redblock_4cyl',
        cylinders: 4,
        turboWhistle: 0.0,
        dieselKnock: 0.0
      },
      description: 'Il celebre "carro armato svedese" progettato per sopravvivere agli inverni scandinavi. Dotato di paraurti telescopici assorbitori, riscaldamento abitacolo ad alta efficienza e motore Redblock con tolleranze eterne.',
      tacticalDaltonAdvice: 'Eccellente stabilità su permafrost e fondo ghiacciato grazie al bilanciamento 50:50. Telaio robustissimo contro gli impatti da animali selvatici e detriti montani.',
      tier: 1,
      unlockType: 'barn_find',
      discoveryPK: 350,
      discoveryLocation: 'Miniera e Draga d\'Oro di Livengood [MP 14]',
      restorationCost: { scrap_metal: 25, spare_tire: 1 },
      restorationStory: 'Appartenuta a un geologo svedese nel 1988. Il celebre motore Redblock B230 è intatto sotto un telo incerato; servono una gomma di scorta e rottami per fissare i manicotti.'
    },

    audi_quattro: {
      id: 'audi_quattro',
      name: 'Ur-Quattro 20V Turbo',
      maker: 'Audi',
      year: 1989,
      country: 'Germania',
      flag: '🇩🇪',
      category: 'Coupé Gran Turismo Integrale',
      engine: '2.2L 5 Cilindri 20V Turbo KKK K24',
      cylinders: 5,
      displacementCc: 2226,
      powerHp: 220,
      torqueNm: 309,
      redlineRpm: 7200,
      idleRpm: 900,
      topSpeedKmh: 230,
      weightKg: 1380,
      drivetrain: 'AWD_TORSEN',
      drivetrainBadge: 'QUATTRO TORSEN + DIFF-LOCK',
      hasTurbo: true,
      turboBoostMaxBar: 1.6,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 70,
      fuelConsumptionRate: 0.046,
      trunkCapacityKg: 100,
      tractionBonus: 1.34,
      handling: {
        agility: 1.1,
        oversteerTendency: 0.2,
        stability: 1.25,
        brakeForce: 38.0,
        groundClearance: 0.15,
        bodyRollFactor: 0.18
      },
      dashTheme: {
        style: 'audi_sport_orange',
        speedoMax: 260,
        redlineRpm: 7200,
        clusterName: 'AUDI SPORT INGOLSTADT',
        dialBg: '#101014',
        tickColor: '#fb923c',
        needleColor: '#f97316',
        accentColor: '#ef4444',
        hasGlowPlug: false,
        hasTurboGauge: true
      },
      soundProfile: {
        baseFreq: 40,
        timbre: 'audi_5cyl_turbo',
        cylinders: 5,
        turboWhistle: 0.8,
        dieselKnock: 0.0
      },
      description: 'La vettura che ha rivoluzionato il motorsport introducendo la trazione integrale permanente nelle competizioni. Motore 5 cilindri turbo dal sound inconfondibile, passaruota bombati e trazione totale permanente Torsen.',
      tacticalDaltonAdvice: 'Velocità impressionante e tenuta sui curvoni del Chandalar Shelf. Richiede attenzione al sottosterzo iniziale all\'ingresso delle curve strette.',
      tier: 4,
      unlockType: 'barn_find',
      discoveryPK: 5800,
      discoveryLocation: 'Continental Divide High Camp - Valico 1.444m [MP 310]',
      restorationCost: { scrap_metal: 75, electronics: 25, cryo_coolant: 1 },
      restorationStory: 'Monumento del rallysmo Group B, collaudata dalla divisione Audi Sport sui ghiacci artici nel 1989. Il 5 cilindri 20V turbo KKK K24 è intatto; con liquido antigelo polare e rottami domina le bufere.'
    },

    bmw_e30_ix: {
      id: 'bmw_e30_ix',
      name: '325iX Touring E30',
      maker: 'BMW',
      year: 1988,
      country: 'Germania',
      flag: '🇩🇪',
      category: 'Sport Wagon Trazione Integrale',
      engine: '2.5L M20B25 6 Cilindri in linea SOHC',
      cylinders: 6,
      displacementCc: 2494,
      powerHp: 170,
      torqueNm: 222,
      redlineRpm: 6600,
      idleRpm: 850,
      topSpeedKmh: 210,
      weightKg: 1310,
      drivetrain: 'AWD_VISCOUS',
      drivetrainBadge: 'ALLRAD 37:63 VISCOUS',
      hasTurbo: false,
      turboBoostMaxBar: 0,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 55,
      fuelConsumptionRate: 0.038,
      trunkCapacityKg: 110,
      tractionBonus: 1.18,
      handling: {
        agility: 1.22,
        oversteerTendency: 0.35,
        stability: 1.15,
        brakeForce: 36.0,
        groundClearance: 0.15,
        bodyRollFactor: 0.2
      },
      dashTheme: {
        style: 'bmw_amber_classic',
        speedoMax: 240,
        redlineRpm: 6600,
        clusterName: 'BMW MOTORENWERKE MÜNCHEN',
        dialBg: '#131110',
        tickColor: '#fdba74',
        needleColor: '#ea580c',
        accentColor: '#f97316',
        hasGlowPlug: false,
        hasTurboGauge: false
      },
      soundProfile: {
        baseFreq: 38,
        timbre: 'bmw_m20_inline6',
        cylinders: 6,
        turboWhistle: 0.0,
        dieselKnock: 0.0
      },
      description: 'La prima serie 3 a quattro ruote motrici con ripartizione della coppia al 37% anteriore e 63% posteriore tramite giunto viscoso epicicloidale. Preserva l\'agilità dinamica tipica BMW su neve e fango.',
      tacticalDaltonAdvice: 'Dinamica di guida esaltante sui fondi a bassa aderenza con sovrasterzo facilmente gestibile. Il telaio touring offre un buon compromesso tra sportività e capacità di carico.',
      tier: 3,
      unlockType: 'barn_find',
      discoveryPK: 2800,
      discoveryLocation: 'Base Radar White Alice - Circolo Polare [MP 200]',
      restorationCost: { scrap_metal: 50, electronics: 18, graphene_battery: 1 },
      restorationStory: 'Utilizzata dagli ufficiali di collegamento della stazione radar durante la Guerra Fredda. La trazione Allrad viscosa 37:63 è pronta a ruggire appena collegata a un accumulatore al grafene.'
    },

    alfa_giulia: {
      id: 'alfa_giulia',
      name: 'Giulia Super 1.6 "Biscione"',
      maker: 'Alfa Romeo',
      year: 1967,
      country: 'Italia',
      flag: '🇮🇹',
      category: 'Berlina Sportiva d\'Epoca',
      engine: '1.6L Bialbero Twin-Cam 2x Weber 40 DCOE',
      cylinders: 4,
      displacementCc: 1570,
      powerHp: 112,
      torqueNm: 150,
      redlineRpm: 6800,
      idleRpm: 900,
      topSpeedKmh: 178,
      weightKg: 1020,
      drivetrain: 'RWD',
      drivetrainBadge: 'RWD BIALBERO SPORT',
      hasTurbo: false,
      turboBoostMaxBar: 0,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 46,
      fuelConsumptionRate: 0.029,
      trunkCapacityKg: 85,
      tractionBonus: 0.82,
      handling: {
        agility: 1.3,
        oversteerTendency: 0.65,
        stability: 0.9,
        brakeForce: 32.0,
        groundClearance: 0.15,
        bodyRollFactor: 0.26
      },
      dashTheme: {
        style: 'veglia_biscione_vintage',
        speedoMax: 200,
        redlineRpm: 7000,
        clusterName: 'VEGLIA BORLETTI MILANO 1967',
        dialBg: '#0e1114',
        tickColor: '#f1f5f9',
        needleColor: '#ffffff',
        accentColor: '#10b981',
        hasGlowPlug: false,
        hasTurboGauge: false
      },
      soundProfile: {
        baseFreq: 44,
        timbre: 'bialbero_carb_4cyl',
        cylinders: 4,
        turboWhistle: 0.0,
        dieselKnock: 0.0
      },
      description: '"Disegnata dal vento": carrozzeria aerodinamica a coda tronca (Kamm tail) con motore interamente in alluminio a doppio albero a camme in testa e cambio a 5 rapporti sincronizzati.',
      tacticalDaltonAdvice: 'Sensibilità di sterzo ed accelerazione brillanti grazie al peso di una tonnellata. Trazione posteriore pura con tendenza al sovrasterzo: richiede rispetto sui ponti di ghiaccio.',
      tier: 3,
      unlockType: 'barn_find',
      discoveryPK: 3500,
      discoveryLocation: 'Bivacco Cava di Sukakpak Mountain [MP 240]',
      restorationCost: { scrap_metal: 50, electronics: 15, engine_oil: 2 },
      restorationStory: 'L\'auto personale di un ingegnere italo-americano della Fluor Corp. I due carburatori Weber doppio corpo del bialbero necessitano di pulizia e olio fresco per cantare a 7.000 giri sulle serpentine montane.'
    },

    peugeot_504_dangel: {
      id: 'peugeot_504_dangel',
      name: '504 Dangel 4x4 Break',
      maker: 'Peugeot / Dangel',
      year: 1980,
      country: 'Francia',
      flag: '🇫🇷',
      category: 'Rally-Raid Safari Station Wagon',
      engine: '2.0L XN1 Inclinato a Carburatore',
      cylinders: 4,
      displacementCc: 1971,
      powerHp: 96,
      torqueNm: 160,
      redlineRpm: 5500,
      idleRpm: 800,
      topSpeedKmh: 145,
      weightKg: 1480,
      drivetrain: '4WD_MANUAL',
      drivetrainBadge: '4WD DANGEL HEAVY-DUTY',
      hasTurbo: false,
      turboBoostMaxBar: 0,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 60,
      fuelConsumptionRate: 0.033,
      trunkCapacityKg: 145,
      tractionBonus: 1.25,
      handling: {
        agility: 0.9,
        oversteerTendency: 0.2,
        stability: 1.1,
        brakeForce: 33.0,
        groundClearance: 0.22,
        bodyRollFactor: 0.32
      },
      dashTheme: {
        style: 'jaeger_french_safari',
        speedoMax: 180,
        redlineRpm: 6000,
        clusterName: 'JAEGER FRANCE OFF-ROAD',
        dialBg: '#131416',
        tickColor: '#e2e8f0',
        needleColor: '#f59e0b',
        accentColor: '#eab308',
        hasGlowPlug: false,
        hasTurboGauge: false
      },
      soundProfile: {
        baseFreq: 35,
        timbre: 'peugeot_xn1_4cyl',
        cylinders: 4,
        turboWhistle: 0.0,
        dieselKnock: 0.0
      },
      description: 'Elaborata da Henry Dangel a Sentheim: telaio rialzato di 22 cm, scatola di rinvio a due velocità con bloccaggio differenziale centrale e sospensioni a lunga escursione nate per i safari africani.',
      tacticalDaltonAdvice: 'Assorbe buche, ciottoli e solchi profondi senza alcuna fatica. Geometria eccellente per superare la pietraia dell\'Atigun Pass e le banchine dissestate dello Yukon.',
      tier: 2,
      unlockType: 'barn_find',
      discoveryPK: 2200,
      discoveryLocation: 'Stazione Idrovore Koyukuk TAPS [MP 145]',
      restorationCost: { scrap_metal: 45, waterproofing_wax: 1, toolkit: 1 },
      restorationStory: 'Ex vettura di supporto della Parigi-Dakar 1980 importata per collaudi polari estremi. La straordinaria luce a terra di 22 cm la rende invincibile sul muskeg una volta sigillati i giunti con cera.'
    },

    golf_country: {
      id: 'golf_country',
      name: 'Golf II Country Syncro',
      maker: 'Volkswagen',
      year: 1990,
      country: 'Germania / Austria',
      flag: '🇩🇪',
      category: 'Crossover Rallye Syncro',
      engine: '1.8L Digifant 8V Iniezione Elettronica',
      cylinders: 4,
      displacementCc: 1781,
      powerHp: 98,
      torqueNm: 143,
      redlineRpm: 6200,
      idleRpm: 850,
      topSpeedKmh: 162,
      weightKg: 1245,
      drivetrain: 'AWD_VISCOUS',
      drivetrainBadge: 'SYNCRO VISCOUS AWD',
      hasTurbo: false,
      turboBoostMaxBar: 0,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 55,
      fuelConsumptionRate: 0.029,
      trunkCapacityKg: 105,
      tractionBonus: 1.16,
      handling: {
        agility: 1.15,
        oversteerTendency: 0.15,
        stability: 1.05,
        brakeForce: 34.0,
        groundClearance: 0.21,
        bodyRollFactor: 0.26
      },
      dashTheme: {
        style: 'vdo_golf_syncro',
        speedoMax: 220,
        redlineRpm: 6200,
        clusterName: 'VDO WOLFSBURG DIGIFANT',
        dialBg: '#0f1316',
        tickColor: '#4ade80',
        needleColor: '#22c55e',
        accentColor: '#16a34a',
        hasGlowPlug: false,
        hasTurboGauge: false
      },
      soundProfile: {
        baseFreq: 41,
        timbre: 'vw_digifant_4cyl',
        cylinders: 4,
        turboWhistle: 0.0,
        dieselKnock: 0.0
      },
      description: 'Prodotta in collaborazione con Steyr-Daimler-Puch a Graz: scocca di Golf II montata su un controtelaio tubolare con altezza da terra di 21 cm, piastre paramotore e ruota di scorta esterna basculante.',
      tacticalDaltonAdvice: 'Il giunto viscoso trasferisce istantaneamente la trazione al posteriore quando le ruote anteriori perdono aderenza sul fango o sulla fanghiglia mista a neve.',
      tier: 2,
      unlockType: 'barn_find',
      discoveryPK: 1500,
      discoveryLocation: 'Officina Camionisti di Coldfoot Camp [MP 115]',
      restorationCost: { scrap_metal: 40, electronics: 12, spare_tire: 1 },
      restorationStory: 'Acquistata da un pilota di bush-plane austriaco per raggiungere le piste isolate. Il telaio tubolare rialzato Syncro è in condizioni impeccabili; bastano pochi cablaggi e una gomma nuova.'
    }
  },

  // Vehicle Parameters (Dynamic default mapped to default vehicle)
  VEHICLE: {
    ACCELERATION: 18.0,
    BRAKE_FORCE: 32.0,
    MAX_SPEED_KMH: 140,
    REVERSE_MAX_SPEED: 35,
    TURN_SPEED: 2.2,
    DRIFT_RECOVERY: 4.5,
    FUEL_CONSUMPTION_RATE: 0.035, // L/sec at full throttle
    IDLE_FUEL_RATE: 0.005,
    OVERHEAT_RATE: 0.08,
    COOLING_RATE: 0.05,
    BATTERY_DRAIN_LIGHTS: 0.02,
    BATTERY_CHARGE_RATE: 0.04,
  },

  // Player On Foot
  PLAYER_FOOT: {
    WALK_SPEED: 4.5,
    SPRINT_SPEED: 8.5,
    STAMINA_DRAIN: 15.0,
    STAMINA_RECOVERY: 20.0,
    INTERACT_RADIUS: 4.0,
  },

  // Survival baseline
  SURVIVAL: {
    MAX_HEALTH: 100,
    MAX_STAMINA: 100,
    MAX_HUNGER: 100,
    MAX_THIRST: 100,
    MAX_HEAT: 100,
    HUNGER_RATE: 0.04,   // per sec
    THIRST_RATE: 0.08,
    FREEZING_TEMP_DAMAGE: 1.5,
    TOXIC_DAMAGE: 2.0,
  },

  // Points of Interest (POIs) - Structured by real-world Dalton Highway infrastructure
  POI_TYPES: {
    SETTLEMENT_HUB: {
      name: 'Insediamento e Stazione di Scambio',
      icon: '🏘️',
      isSettlement: true,
      lootTable: [], // Trade hub, not simple scavenge
      dangerLevel: 0.05
    },
    COASTAL_FISHERY_RUIN: {
      name: 'Vecchia Tonnara & Rimessa Motoscafi Costiera',
      icon: '⚓',
      biomeId: 'mediterranean_coast',
      lootTable: ['refined_fuel', 'engine_oil', 'scrap_metal', 'water_purified'],
      dangerLevel: 0.2,
      loreNote: 'Antico magazzino marinaro affacciato sulle scogliere. Tra le reti da pesca ci sono taniche di benzina marina e filtri decantatori intatti.'
    },
    FORESTRY_LUMBER_YARD: {
      name: 'Segheria Idraulica & Deposito Faggi',
      icon: '🪵',
      biomeId: 'temperate_forest',
      lootTable: ['cured_timber', 'antiseptic_resin', 'first_aid_bandage', 'toolkit'],
      dangerLevel: 0.2,
      loreNote: 'Accatastamento di travi di quercia e faggio stagionato. Sotto la tettoia i mastri boscaioli hanno lasciato casse di attrezzi e resine sigillanti.'
    },
    DESERT_CARAVAN_POST: {
      name: 'Forte Carovaniero & Cisterna delle Dune',
      icon: '🌴',
      biomeId: 'arid_desert',
      lootTable: ['water_purified', 'waterproofing_wax', 'fuel_canister', 'spare_tire'],
      dangerLevel: 0.35,
      loreNote: 'Antico presidio carovaniero tra le sabbie del Sahara. La cisterna sotterranea protegge preziose taniche d\'acqua e teli termoriflettenti.'
    },
    SAVANNA_RANGER_STATION: {
      name: 'Torretta di Vedetta & Deposito Ranger del Bush',
      icon: '🦁',
      biomeId: 'savanna_steppe',
      lootTable: ['reinforced_coil', 'armor_plate', 'toolkit', 'canned_stew'],
      dangerLevel: 0.3,
      loreNote: 'Stazione dei guardaparco della savana. Nell\'armeria e nell\'officina si trovano balestre rinforzate e lamiere d\'acciaio per rinforzare il pianale.'
    },
    JUNGLE_BOTANICAL_LAB: {
      name: 'Stazione Idrologica & Scalo Rio Verde',
      icon: '🌿',
      biomeId: 'tropical_rainforest',
      lootTable: ['peat_filter', 'waterproofing_wax', 'antiseptic_resin', 'spare_tire'],
      dangerLevel: 0.4,
      loreNote: 'Laboratorio palafittato di ricerca idrologica. I filtri a torba e le cere impermeabilizzanti per i circuiti elettrici sono ancora sigillati.'
    },
    ALPINE_TUNNEL_SHELTER: {
      name: 'Galleria Paravalanghe & Cava del Valico',
      icon: '🏔️',
      biomeId: 'alpine_peaks',
      lootTable: ['tungsten_drill_bit', 'reinforced_coil', 'armor_plate', 'scrap_metal'],
      dangerLevel: 0.45,
      loreNote: 'Riparo scavato nella parete granitica per i cantonieri del passo. Si possono recuperare inserti al tungsteno e balestre speciali da salita.'
    },
    TAIGA_LOGGING_DEPOT: {
      name: 'Scalo Zattere & Deposito Conifere della Taiga',
      icon: '🌲',
      biomeId: 'boreal_taiga',
      lootTable: ['cured_timber', 'cryo_coolant', 'thermal_lining', 'toolkit'],
      dangerLevel: 0.35,
      loreNote: 'Piazzale di smistamento tronchi lungo il fiume gelato. Nelle casse stagne ci sono flaconi di glicole criogenico e coperte termiche.'
    },
    POLAR_METAR_SHELTER: {
      name: 'Capsula Rifugio Polare 80° Parallelo',
      icon: '❄️',
      biomeId: 'polar_tundra',
      lootTable: ['cryo_coolant', 'thermal_lining', 'electronics', 'water_purified'],
      dangerLevel: 0.5,
      loreNote: 'Modulo geodetico del consorzio polare. Custodisce sensori satellitari schermati e fluido antigelo artico in grado di reggere a -55°C.'
    },
    OVERTURNED_CONVOY: {
      name: 'Autocarro da Spedizione Ribaltato',
      icon: '🚛',
      lootTable: ['fuel_canister', 'spare_tire', 'toolkit', 'scrap_metal'],
      dangerLevel: 0.4,
      loreNote: 'Un camion del convoglio precedente è uscito di carreggiata. Nel vano di carico ci sono carburante di riserva e ruote di scorta ancora gonfie.'
    },
    MILITARY_CHECKPOINT: {
      name: 'Posto di Blocco & Stazione Radio Transcontinentale',
      icon: '🚧',
      lootTable: ['ammo_flare', 'armor_plate', 'medkit', 'canned_stew'],
      dangerLevel: 0.45,
      loreNote: 'Barriera di confine con antenna ricetrasmittente d\'emergenza. All\'interno si trovano razzi di segnalazione e razioni alimentari.'
    }
  },

  // Modular Engineering Upgrades (4 Branches: Chassis, Powertrain, Armor, Avionics)
  UPGRADES: {
    // 1. ASSETTO & TRAZIONE (Chassis & Grip)
    STUDDED_TIRES: {
      id: 'studded_tires',
      category: 'chassis',
      categoryName: 'Assetto & Trazione',
      icon: '🛞',
      name: 'Pneumatici Chiodati Nokian Hakkapeliitta',
      cost: { scrap_metal: 25, spare_tire: 1 },
      desc: '+35% aderenza su ghiaccio e permafrost; riduce del 25% la distanza di arresto su fondo scivoloso.',
      statLabel: '+35% Grip Ghiaccio & Neve'
    },
    RALLY_SUSPENSION: {
      id: 'rally_suspension',
      category: 'chassis',
      categoryName: 'Assetto & Trazione',
      icon: '🌀',
      name: 'Assetto Rialzato Bilstein & Molle Heavy-Duty',
      cost: { scrap_metal: 35, toolkit: 1 },
      desc: '+5 cm luce libera a terra; assorbe il 65% dei danni da buche e dossi ed elimina l\'affossamento sulla ghiaia.',
      statLabel: '+5cm Luce / -65% Danni Buche'
    },
    DIFF_LOCK_LSD: {
      id: 'diff_lock_lsd',
      category: 'chassis',
      categoryName: 'Assetto & Trazione',
      icon: '⚙️',
      name: 'Differenziale Autobloccante Meccanico LSD',
      cost: { scrap_metal: 45, electronics: 15, engine_oil: 1 },
      desc: 'Elimina lo slittamento della ruota scarica sui fondi misti asfalto/neve/fango; +20% spinta e tenuta in accelerazione.',
      statLabel: '+20% Trazione Coppia Mista'
    },

    // 2. MOTORE & TERMO (Powertrain & Cold Weather)
    BLOCK_HEATER: {
      id: 'block_heater',
      category: 'engine',
      categoryName: 'Motore & Termo',
      icon: '🔥',
      name: 'Preriscaldatore Ausiliario Webasto Polare',
      cost: { scrap_metal: 30, fuel_canister: 1, electronics: 10 },
      desc: 'Mantiene il blocco motore a 45°C anche a -40°C esterni; azzera l\'usura delle partenze a freddo e il consumo batteria.',
      statLabel: 'Partenza Istantanea a -40°C'
    },
    COPPER_RADIATOR: {
      id: 'copper_radiator',
      category: 'engine',
      categoryName: 'Motore & Termo',
      icon: '❄️',
      name: 'Radiatore Maggiorato in Rame a 3 Fila',
      cost: { scrap_metal: 35, engine_oil: 1 },
      desc: 'Dimezza il surriscaldamento sotto sforzo continuo; impedisce il congelamento del liquido antigelo nei valichi montani.',
      statLabel: 'Raffreddamento Rame Stabile 80°C'
    },
    TURBO_BOOST_KIT: {
      id: 'turbo_boost_kit',
      category: 'engine',
      categoryName: 'Motore & Termo',
      icon: '💨',
      name: 'Kit Intercooler & Wastegate da Gara',
      cost: { scrap_metal: 50, electronics: 20 },
      desc: '+0.35 Bar di pressione di sovralimentazione massima (+18% spinta e accelerazione); scarico pop-off e fischio turbo amplificati.',
      statLabel: '+0.35 Bar Boost Turbo & +18% Spinta'
    },
    SNORKEL_INTAKE: {
      id: 'snorkel_intake',
      category: 'engine',
      categoryName: 'Motore & Termo',
      icon: '🤿',
      name: 'Snorkel con Prefiltro Polveri Ciclonico',
      cost: { scrap_metal: 25, toolkit: 1 },
      desc: 'Aspirazione alta sul montante del tetto: consente di guadare acquitrini e fiumi allagati proteggendo il motore da fango e sabbia.',
      statLabel: 'Guado Acqua & Protezione Filtri'
    },

    // 3. TELAIO & AUTONOMIA (Armor & Range)
    SKID_PLATE: {
      id: 'skid_plate',
      category: 'armor',
      categoryName: 'Telaio & Autonomia',
      icon: '🛡️',
      name: 'Slitta Paracoppa in Duralluminio Forgiato',
      cost: { scrap_metal: 35, armor_plate: 1 },
      desc: 'Protegge coppa dell\'olio, campana frizione e scarico; dimezza i danni da impatto con sassi, massi caduti e cunette.',
      statLabel: '-50% Danno da Pietrisco & Massi'
    },
    HEAVY_BULLBAR: {
      id: 'heavy_bullbar',
      category: 'armor',
      categoryName: 'Telaio & Autonomia',
      icon: '🦬',
      name: 'Rostro Frontale Corazzato Spingitutto',
      cost: { scrap_metal: 45, toolkit: 1 },
      desc: 'Riduce del 70% i danni da impatto frontale; demolisce fusti di cantiere e tronchi leggeri senza arrestare la marcia.',
      statLabel: '-70% Danno Frontale / Spinta Ostacoli'
    },
    AUX_FUEL_CELL: {
      id: 'aux_fuel_cell',
      category: 'armor',
      categoryName: 'Telaio & Autonomia',
      icon: '⛽',
      name: 'Serbatoio Ausiliario Coibentato (+40L)',
      cost: { scrap_metal: 40, fuel_canister: 2 },
      desc: 'Aggiunge un serbatoio ausiliario blindato da 40 litri, raddoppiando l\'autonomia nei lunghi tratti deserti della Haul Road.',
      statLabel: '+40 Litri Serbatoio Carburante'
    },
    ROOF_CARGO_RACK: {
      id: 'roof_cargo_rack',
      category: 'armor',
      categoryName: 'Telaio & Autonomia',
      icon: '📦',
      name: 'Portapacchi da Tetto Expedition Heavy-Duty',
      cost: { scrap_metal: 30, cured_timber: 2 },
      desc: 'Struttura tubolare aerodinamica sul padiglione: aumenta la portata massima di carico del bagagliaio di +45 kg su qualsiasi vettura.',
      statLabel: '+45 kg Capacità Bagagliaio'
    },

    // 4. AVIONICA & VISIONE (Avionics & Optics)
    RALLY_LIGHT_BAR: {
      id: 'rally_light_bar',
      category: 'avionics',
      categoryName: 'Avionica & Visione',
      icon: '💡',
      name: 'Barra 4 Fari di Profondità Hella Rally 2000',
      cost: { scrap_metal: 30, electronics: 20 },
      desc: 'Raddoppia la gittata dei fari fino a 70 metri con fascio allargato; fende la nebbia fitta, le bufere di neve e la notte polare.',
      statLabel: 'Gittata Fari 70m Fascio Largo'
    },
    CB_RADAR_SCANNER: {
      id: 'cb_radar_scanner',
      category: 'avionics',
      categoryName: 'Avionica & Visione',
      icon: '📡',
      name: 'Radio CB Dalton Convoy & Georadar Ostacoli',
      cost: { scrap_metal: 35, electronics: 25 },
      desc: 'Scansiona la carreggiata e notifica con segnale acustico e allarme visivo sulla plancia gli ostacoli e le buche con 120m di anticipo.',
      statLabel: 'Radar Ostacoli & Allarme CB 120m'
    },
    AGM_DUAL_BATTERY: {
      id: 'agm_dual_battery',
      category: 'avionics',
      categoryName: 'Avionica & Visione',
      icon: '🔋',
      name: 'Doppia Batteria AGM al Gel Deep-Cycle',
      cost: { scrap_metal: 25, electronics: 15 },
      desc: 'Capacità elettrica raddoppiata e ricarica ultra-rapida; immunità totale ai cali di tensione e blackout delle tempeste ioniche.',
      statLabel: 'Immunità Elettrica & 2x Ricarica'
    },

    // Backwards compatibility aliases
    BULLBAR: { id: 'heavy_bullbar', name: 'Rostro Frontale Corazzato', cost: { scrap_metal: 45, toolkit: 1 }, desc: 'Riduce del 70% i danni frontali al veicolo e demolisce ostacoli leggeri.', statLabel: '-70% Danno Frontale' },
    ROOF_LIGHTS: { id: 'rally_light_bar', name: 'Barra Fari Ausiliari a LED', cost: { scrap_metal: 30, electronics: 20 }, desc: 'Raddoppia il raggio e l\'ampiezza del fascio luminoso nella nebbia.', statLabel: 'Gittata Fari 70m' },
    OFFROAD_TIRES: { id: 'studded_tires', name: 'Pneumatici Chiodati M+S', cost: { scrap_metal: 25, spare_tire: 1 }, desc: 'Aumenta la trazione su fango (+40%) e ghiaccio (+70%).', statLabel: '+35% Grip Ghiaccio' },
    AUX_TANK: { id: 'aux_fuel_cell', name: 'Serbatoio Ausiliario Blindato', cost: { scrap_metal: 40, fuel_canister: 2 }, desc: 'Aumenta la capienza del carburante da 50L a 90L.', statLabel: '+40L Serbatoio' },
    TURBO_COOLER: { id: 'copper_radiator', name: 'Radiatore Maggiorato ad Aria', cost: { scrap_metal: 35, engine_oil: 1 }, desc: 'Dimezza il surriscaldamento del motore a velocità sostenute.', statLabel: 'Raffreddamento Rame' },
    ARMORED_HULL: { id: 'skid_plate', name: 'Pannelli di Blindatura Composita', cost: { scrap_metal: 35, armor_plate: 1 }, desc: 'Aumenta l\'integrità strutturale del veicolo del 50%.', statLabel: '-50% Danno Sassi' }
  }
};
