/**
 * THE LONG MERIDIAN - Configuration & Game Constants
 */

export const CONFIG = {
  VERSION: '1.0.0',
  GAME_TITLE: 'THE LONG MERIDIAN',
  SUBTITLE: 'Northern Survival Corridor',

  // World & Generation
  WORLD: {
    CHUNK_LENGTH: 80,          // Length of each procedural road chunk (meters)
    VISIBLE_CHUNKS: 5,         // Number of chunks rendered ahead/behind
    ROAD_SEGMENTS_PER_CHUNK: 20,
    BASE_ROAD_WIDTH: 24.0,     // Generous 24m highway (2 wide travel lanes + emergency shoulders)
    DESPAWN_DISTANCE: 70,      // Distance behind player to recycle chunks
    ROAD_Y: 0,
  },

  // Biomes definitions based on the real-world Dalton Highway (Alaska Route 11 / The Haul Road)
  BIOMES: {
    RUSTY_PERIPHERY: {
      id: 'rusty_periphery',
      sectorIndex: 0,
      name: 'Fox & Goldstream Valley',
      subname: 'Distretto Minerario di Fairbanks [MP 0 - 56]',
      loreTitle: 'Cintura della Corsa all\'Oro & Scali della Alaska Railroad',
      history: 'Storico distretto minerario dell\'entroterra alaskano, sviluppatosi attorno alla valle aurifera di Goldstream e alla gigantesca Gold Dredge No. 8 scoperta dopo la corsa all\'oro del 1902. Le officine della vecchia ferrovia Alaska Railroad conservano scorte di gasolio pesante e carpenteria industriale, ma l\'acqua di falda è compromessa dai residui di estrazione.',
      settlementName: 'Fox Junction & Gold Dredge 8',
      settlementPK: 220, // meters from start (Milepost ~11)
      colorSky: 0x221a18,
      colorFog: 0x1f1614,
      colorGround: 0x2c2621,
      colorRoad: 0x3d3936,
      fogDensity: 0.018,
      ambientIntensity: 0.45,
      sunIntensity: 0.6,
      sunColor: 0xffd4aa,
      roadRoughness: 0.4,
      tractionFactor: 0.95,
      weatherTypes: ['smog', 'acid_drizzle', 'clear'],
      hazardFrequency: 0.35,
      musicMood: 'industrial_drone',
      environmentalThreat: 'Polveri ferrose e residui della miniera: sporcano i radiatori e accelerano il surriscaldamento a pieno carico.',
      primaryExport: ['refined_fuel', 'scrap_metal', 'engine_oil'],
      criticalNeed: ['water_purified', 'canned_stew', 'medkit'],
      recommendedGear: 'Filtro di aspirazione pulito, scorte d\'acqua pura per la taiga'
    },
    BLACK_PINE_WOODS: {
      id: 'black_pine_woods',
      sectorIndex: 1,
      name: 'Yukon River Taiga',
      subname: 'Ponte E.L. Patton & Stevens Village [MP 56 - 115]',
      loreTitle: 'Foreste di Picea Nera & Bacino del Fiume Yukon',
      history: 'Il tratto in cui la Dalton Highway incontra il monumentale fiume Yukon, attraversato dall\'imponente E.L. Patton Bridge lungo 700 metri su cui corre la Trans-Alaska Pipeline. La Pump Station 6 sorge accanto all\'antico insediamento Athabaskan di Stevens Village. I taglialegna e i nativi ricavano mastice sigillante e legname denso dalla picea nera, ma mancano di carburante raffinato.',
      settlementName: 'Yukon River Camp & Pump Station 6',
      settlementPK: 870, // meters (Milepost ~56)
      colorSky: 0x0b1410,
      colorFog: 0x08120d,
      colorGround: 0x152219,
      colorRoad: 0x242e20,
      fogDensity: 0.024,
      ambientIntensity: 0.35,
      sunIntensity: 0.4,
      sunColor: 0x88ccaa,
      roadRoughness: 0.7,
      tractionFactor: 0.8,
      weatherTypes: ['heavy_mist', 'rain', 'overcast'],
      hazardFrequency: 0.45,
      musicMood: 'dark_forest',
      environmentalThreat: 'Ceppi e radici affioranti lungo le banchine umide: impatti violenti se si superano i 65 km/h, nebbia fluviale ghiacciata.',
      primaryExport: ['antiseptic_resin', 'cured_timber', 'first_aid_bandage'],
      criticalNeed: ['fuel_canister', 'toolkit', 'scrap_metal'],
      recommendedGear: 'Fari ausiliari da tetto contro la nebbia fluviale, sospensioni alte'
    },
    FLOODED_MARSHLAND: {
      id: 'flooded_marshland',
      sectorIndex: 2,
      name: 'Koyukuk Flats & Coldfoot',
      subname: 'Piane Alluvionali & Slate Creek [MP 115 - 200]',
      loreTitle: 'Pantano Subartico e Sosta Camionisti di Coldfoot',
      history: 'Fondata nel 1898 durante la corsa all\'oro di Slate Creek, quando i cercatori "got cold feet" (ebbero i piedi freddi) e abbandonarono l\'impresa. Negli anni \'70 divenne il punto di sosta vitale per i camionisti dell\'oleodotto. Il terreno circostante è dominato dal famigerato "muskeg": torbiera alluvionale e fango che intrappolano anche gli autocarri a trazione integrale.',
      settlementName: 'Coldfoot Truck Stop & Slate Creek',
      settlementPK: 1520, // meters (Milepost ~175)
      colorSky: 0x101b22,
      colorFog: 0x0d161d,
      colorGround: 0x142028,
      colorRoad: 0x1f2930,
      fogDensity: 0.022,
      ambientIntensity: 0.4,
      sunIntensity: 0.5,
      sunColor: 0x90c8e0,
      roadRoughness: 0.6,
      tractionFactor: 0.65,
      weatherTypes: ['torrential_rain', 'dense_fog'],
      hazardFrequency: 0.5,
      musicMood: 'aquatic_melancholy',
      environmentalThreat: 'Fango acquitrinoso "muskeg" e aquaplaning: altissima resistenza al rotolamento, affondamento ruote e surriscaldamento motore.',
      primaryExport: ['peat_filter', 'waterproofing_wax', 'water_purified'],
      criticalNeed: ['spare_tire', 'electronics', 'engine_oil'],
      recommendedGear: 'Pneumatici M+S tassellati, cera impermeabilizzante per giunti'
    },
    GLASS_CRATER: {
      id: 'glass_crater',
      sectorIndex: 3,
      name: 'Arctic Circle & Chandalar',
      subname: 'Parallelo 66° 33\' N & DEW Line [MP 200 - 270]',
      loreTitle: 'Altopiano del Circolo Polare & Antenne Radar della Guerra Fredda',
      history: 'Il punto in cui la Dalton Highway varca ufficialmente la latitudine 66° 33\' 48" Nord, entrando nel Circolo Polare Artico. A Chandalar Shelf si trovano i resti della stazione radar della DEW Line (Distant Early Warning) del sistema White Alice. Gli ingegneri superstiti custodiscono batterie al grafene e circuiti schermati contro le tempeste geomagnetiche dell\'aurora.',
      settlementName: 'Chandalar Shelf - Base Radar White Alice',
      settlementPK: 2170, // meters (Milepost ~244)
      colorSky: 0x160d26,
      colorFog: 0x130a21,
      colorGround: 0x1b122c,
      colorRoad: 0x2c1a45,
      fogDensity: 0.02,
      ambientIntensity: 0.35,
      sunIntensity: 0.7,
      sunColor: 0xd494ff,
      roadRoughness: 0.5,
      tractionFactor: 0.88,
      weatherTypes: ['ion_storm', 'aurora_static'],
      hazardFrequency: 0.6,
      radiationDanger: true,
      musicMood: 'anomalous_pulse',
      environmentalThreat: 'Tempeste geomagnetiche e interferenze ioniche dell\'Aurora: disturbi all\'alternatore, cali di tensione e blackout delle luci.',
      primaryExport: ['graphene_battery', 'rad_shield_plate', 'electronics'],
      criticalNeed: ['canned_stew', 'water_purified', 'first_aid_bandage'],
      recommendedGear: 'Cavi elettrici schermati, fusibili ausiliari'
    },
    IRON_GORGE: {
      id: 'iron_gorge',
      sectorIndex: 4,
      name: 'Atigun Pass & Brooks Range',
      subname: 'Passo Atigun 1.444m - Continental Divide [MP 270 - 340]',
      loreTitle: 'Valico Alpino delle Montagne Brooks & Falesie di Roccia Nera',
      history: 'Il punto più alto e pericoloso dell\'intera rete stradale alaskana: il valico dell\'Atigun Pass a 1.444 metri di quota attraverso la catena montuosa delle Brooks Range. Noto tra i camionisti come "The Shelf", presenta pendenze del 12% su sterrato battuto, strapiombi di centinaia di metri, caduta massi di ardesia tagliente e venti sferzanti a 140 km/h.',
      settlementName: 'Atigun Pass High Camp - Cava dei Convogli',
      settlementPK: 2820, // meters (Milepost ~290)
      colorSky: 0x241410,
      colorFog: 0x20100d,
      colorGround: 0x3a2219,
      colorRoad: 0x482f25,
      fogDensity: 0.016,
      ambientIntensity: 0.5,
      sunIntensity: 0.75,
      sunColor: 0xff9966,
      roadRoughness: 0.85,
      tractionFactor: 0.75,
      weatherTypes: ['gale_winds', 'rock_dust'],
      hazardFrequency: 0.55,
      musicMood: 'desert_wind',
      environmentalThreat: 'Pietraia tagliente da franamento e raffiche di burrasca: lacerazione improvvisa dei battistrada e instabilità dello sterzo.',
      primaryExport: ['reinforced_coil', 'tungsten_drill_bit', 'armor_plate'],
      criticalNeed: ['fuel_canister', 'refined_fuel', 'canned_stew'],
      recommendedGear: 'Rostro corazzato paramassi, gomme con mescola anti-taglio'
    },
    PERMAFROST_HIGHLANDS: {
      id: 'permafrost_highlands',
      sectorIndex: 5,
      name: 'Deadhorse & Prudhoe Bay',
      subname: 'Mar Glaciale Artico & Mare di Beaufort [MP 340 - 414]',
      loreTitle: 'Città Modulare sul Permafrost & Terminale dell\'Oceano Artico',
      history: 'Il capolinea assoluto della Dalton Highway sulle sponde ghiacciate del Mar Glaciale Artico. Costruita nel 1968 per l\'estrazione petrolifera gigante di Prudhoe Bay, la cittadella di Deadhorse poggia interamente su pilastri e banchi di ghiaia isolante per non fondere il permafrost continuo. Qui la temperatura scende stabilmente sotto i -45°C.',
      settlementName: 'Deadhorse Terminal & Base Prudhoe Bay',
      settlementPK: 3470, // meters (Milepost ~414)
      colorSky: 0x101a24,
      colorFog: 0x14202c,
      colorGround: 0x283848,
      colorRoad: 0x3b4c5c,
      fogDensity: 0.028,
      ambientIntensity: 0.45,
      sunIntensity: 0.5,
      sunColor: 0xcfe8ff,
      roadRoughness: 0.5,
      tractionFactor: 0.45, // very slippery!
      weatherTypes: ['blizzard', 'freezing_rain'],
      hazardFrequency: 0.65,
      coldDanger: true,
      musicMood: 'cold_isolation',
      environmentalThreat: 'Gelo polare a -45°C e lastroni di ghiaccio nero: il radiatore gela all\'istante a motore spento; trazione minima a 0.35.',
      primaryExport: ['cryo_coolant', 'thermal_lining', 'toolkit'],
      criticalNeed: ['spare_tire', 'fuel_canister', 'engine_oil'],
      recommendedGear: 'Glicole criogenico antigelo, pneumatici chiodati'
    }
  },

  // Major Real-World Settlements along the Dalton Highway (Alaska Route 11)
  SETTLEMENTS: {
    fox_junction: {
      id: 'fox_junction',
      biomeId: 'rusty_periphery',
      pk: 220,
      name: 'Fox Junction & Gold Dredge 8',
      faction: 'Gilda dei Minatori e Ferrovieri di Fairbanks',
      population: 85,
      icon: '⛏️',
      description: 'Cittadella fortificata attorno alla gigantesca Gold Dredge No. 8 nella valle di Goldstream. I meccanici mantengono operativi i vecchi compressori e scambiano gasolio pesante e profilati d\'acciaio in cambio di cibo pulito e filtri per l\'acqua.',
      tacticalAdvice: 'Fai scorta di carburante pesante qui a Fox: a nord del fiume Yukon non ci sono raffinerie e i boscaioli pagheranno il gasolio al triplo.',
      buysMultiplier: 2.5,
      sellsDiscount: 0.7
    },
    yukon_crossing: {
      id: 'yukon_crossing',
      biomeId: 'black_pine_woods',
      pk: 870,
      name: 'Yukon River Camp & Pump Station 6',
      faction: 'Comunità Nativa e Tecnici della Pipeline Yukon',
      population: 62,
      icon: '🌉',
      description: 'Avamposto strategico ai piedi dell\'imponente ponte E.L. Patton Bridge sul fiume Yukon. I residenti vigilano sulle valvole di derivazione della Pipeline e distillano resina fenolica di picea nera per sigillare radiatori e scafi.',
      tacticalAdvice: 'Acquista resina sigillante per le forature e il radiatore. La comunità ti pagherà caro qualsiasi litro di carburante portato da Fox.',
      buysMultiplier: 2.5,
      sellsDiscount: 0.7
    },
    coldfoot_camp: {
      id: 'coldfoot_camp',
      biomeId: 'flooded_marshland',
      pk: 1520,
      name: 'Coldfoot Truck Stop & Slate Creek',
      faction: 'Fratellanza dei Camionisti Artici (Haul Road Drivers)',
      population: 110,
      icon: '🚛',
      description: 'Il mitico punto di sosta per i convogli polari alle porte del fiume Koyukuk. Circondato dal muskeg, fornisce torba di tundra drenante e cera idrorepellente per proteggere i circuiti dal fango acido.',
      tacticalAdvice: 'Il fango muskeg delle piane di Koyukuk consuma gli pneumatici e blocca le ruote. Rifornisciti di cere protettive prima della traversata.',
      buysMultiplier: 2.5,
      sellsDiscount: 0.7
    },
    chandalar_shelf: {
      id: 'chandalar_shelf',
      biomeId: 'glass_crater',
      pk: 2170,
      name: 'Chandalar Shelf - Base Radar White Alice',
      faction: 'Presidio Militare Scientifico DEW Line',
      population: 40,
      icon: '📡',
      description: 'Ex stazione radar troposferica per la difesa aerea della Guerra Fredda. Gli operatori gestiscono banchi accumulatori schermati al grafene e parabole di ascolto per monitorare le tempeste solari.',
      tacticalAdvice: 'Le aurore boreali causano sovratensioni magnetiche all\'alternatore. Installa condensatori schermati per non rimanere al buio.',
      buysMultiplier: 2.5,
      sellsDiscount: 0.7
    },
    atigun_camp: {
      id: 'atigun_camp',
      biomeId: 'iron_gorge',
      pk: 2820,
      name: 'Atigun Pass High Camp - Cava dei Convogli',
      faction: 'Guardia Valanghe e Minatori delle Brooks Range',
      population: 94,
      icon: '🏔️',
      description: 'Rifugio fortificato ricavato nelle falesie scistose sotto la vetta dell\'Atigun Pass (1.444m). I fabbri forgiano balestre da carico pesanti e chiodi al tungsteno per impedire lo slittamento nei canaloni.',
      tacticalAdvice: 'La salita dell\'Atigun ha pendenze micidiali e pietre taglienti. Monta balestre rinforzate e paramotore per evitare la rottura delle sospensioni.',
      buysMultiplier: 2.5,
      sellsDiscount: 0.7
    },
    deadhorse_terminal: {
      id: 'deadhorse_terminal',
      biomeId: 'permafrost_highlands',
      pk: 3470,
      name: 'Deadhorse Terminal & Base Prudhoe Bay',
      faction: 'Consorzio Energetico dell\'Oceano Artico (Beaufort Sea)',
      population: 35,
      icon: '❄️',
      description: 'L\'estremo terminale della Dalton Highway affacciato sul Mar Glaciale Artico. Costruito interamente su palafitte per non scaldare il permafrost. Producono fluido criogenico antigelo capace di resistere a -55°C.',
      tacticalAdvice: 'A Deadhorse la temperatura scende a -45°C. Se spegni il motore senza refrigerante criogenico, il circuito di raffreddamento si spaccherà.',
      buysMultiplier: 2.5,
      sellsDiscount: 0.7
    }
  },

  // Surface materials details
  SURFACES: {
    ASPHALT: { name: 'Asfalto Fessurato', friction: 1.0, wearMultiplier: 1.0, sound: 'asphalt' },
    DIRT: { name: 'Fango Argilloso', friction: 0.75, wearMultiplier: 1.4, sound: 'dirt' },
    GRAVEL: { name: 'Ghiaia e Detriti', friction: 0.8, wearMultiplier: 1.3, sound: 'gravel' },
    ICE: { name: 'Ghiaccio Nero', friction: 0.35, wearMultiplier: 0.8, sound: 'ice' },
    SLUDGE: { name: 'Fanghiglia Tossica', friction: 0.6, wearMultiplier: 2.0, toxicity: 8, sound: 'sludge' },
    STEEL_BRIDGE: { name: 'Grigliato d\'Acciaio', friction: 0.9, wearMultiplier: 1.1, sound: 'metal' }
  },

  // Real European Classic Vehicles Catalog (1960s - 2000s)
  DEFAULT_VEHICLE_ID: 'panda_4x4',

  VEHICLES_CATALOG: {
    panda_4x4: {
      id: 'panda_4x4',
      name: 'Panda 4x4 Steyr-Puch',
      maker: 'Fiat',
      year: 1983,
      country: 'Italia / Austria',
      flag: '🇮🇹',
      category: 'Utilitaria Integrale Leggera',
      engine: '965cc A112 Asta e Bilancieri',
      cylinders: 4,
      displacementCc: 965,
      powerHp: 48,
      torqueNm: 74,
      redlineRpm: 6000,
      idleRpm: 850,
      topSpeedKmh: 135,
      weightKg: 780,
      drivetrain: '4WD_MANUAL',
      drivetrainBadge: '4WD STEYR INSERIBILE',
      hasTurbo: false,
      turboBoostMaxBar: 0,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 35,
      fuelConsumptionRate: 0.024,
      trunkCapacityKg: 85,
      tractionBonus: 1.15,
      handling: {
        agility: 1.25,
        oversteerTendency: 0.1,
        stability: 0.85,
        brakeForce: 30.0,
        groundClearance: 0.19,
        bodyRollFactor: 0.28
      },
      dashTheme: {
        style: 'veglia_minimal',
        speedoMax: 160,
        redlineRpm: 6000,
        clusterName: 'VEGLIA BORLETTI PANDA',
        dialBg: '#12161a',
        tickColor: '#94a3b8',
        needleColor: '#f97316',
        accentColor: '#22c55e',
        hasGlowPlug: false,
        hasTurboGauge: false
      },
      soundProfile: {
        baseFreq: 42,
        timbre: 'raspy_4cyl',
        cylinders: 4,
        turboWhistle: 0.0,
        dieselKnock: 0.0
      },
      description: 'Progettata da Giorgetto Giugiaro con trazione integrale sviluppata da Steyr-Puch a Graz. Pesa appena 780 kg e dispone della leggendaria "primina" ultra-corta che le permette di arrampicarsi su pendenze del 50%.',
      tacticalDaltonAdvice: 'La leggerezza eccezionale le impedisce di sprofondare nel fango muskeg del Koyukuk e sulla neve fresca. Manca di potenza sulla salita dell\'Atigun Pass a pieno carico.',
      tier: 1,
      unlockType: 'default',
      discoveryPK: 0,
      discoveryLocation: 'Livengood Staging Post [MP 0]',
      restorationCost: {},
      restorationStory: 'La tua fidata compagna di partenza: leggera, agile e dotata della leggendaria primina Steyr-Puch.'
    },

    delta_integrale: {
      id: 'delta_integrale',
      name: 'Delta HF Integrale Evoluzione',
      maker: 'Lancia',
      year: 1991,
      country: 'Italia',
      flag: '🇮🇹',
      category: 'Rally Special Gr.A WRC',
      engine: '2.0L 16V Turbo Garrett T3 Intercooler',
      cylinders: 4,
      displacementCc: 1995,
      powerHp: 210,
      torqueNm: 300,
      redlineRpm: 6800,
      idleRpm: 950,
      topSpeedKmh: 220,
      weightKg: 1300,
      drivetrain: 'AWD_TORSEN',
      drivetrainBadge: 'TORSEN AWD 47:53',
      hasTurbo: true,
      turboBoostMaxBar: 1.4,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 57,
      fuelConsumptionRate: 0.048,
      trunkCapacityKg: 95,
      tractionBonus: 1.35,
      handling: {
        agility: 1.2,
        oversteerTendency: 0.25,
        stability: 1.15,
        brakeForce: 38.0,
        groundClearance: 0.14,
        bodyRollFactor: 0.16
      },
      dashTheme: {
        style: 'veglia_rally_yellow',
        speedoMax: 260,
        redlineRpm: 6800,
        clusterName: 'VEGLIA COMPETIZIONE CORSE',
        dialBg: '#0f1115',
        tickColor: '#eab308',
        needleColor: '#ef4444',
        accentColor: '#eab308',
        hasGlowPlug: false,
        hasTurboGauge: true
      },
      soundProfile: {
        baseFreq: 39,
        timbre: 'rally_turbo_4cyl',
        cylinders: 4,
        turboWhistle: 0.85,
        dieselKnock: 0.0
      },
      description: 'Regina incontrastata di 6 titoli mondiali rally costruttori consecutivi. Trazione integrale permanente con differenziale epicicloidale e giunto Ferguson centrale abbinato al differenziale Torsen posteriore.',
      tacticalDaltonAdvice: 'Velocità e tenuta laterale devastanti sui tratti veloci di ghiaia battuta. Fai attenzione al consumo carburante elevato e all\'entrata repentina della turbina Garrett sui fondi ghiacciati.',
      tier: 4,
      unlockType: 'barn_find',
      discoveryPK: 6500,
      discoveryLocation: 'Hangar Spedizione Polare Deadhorse [MP 414]',
      restorationCost: { scrap_metal: 85, electronics: 30, armor_plate: 1, graphene_battery: 1 },
      restorationStory: 'La leggenda dei 6 titoli mondiali rally costruttori consecutivi. Nascosta nell\'hangar terminale di Deadhorse sul Mar Glaciale Artico. Trasferisce 210 CV alle 4 ruote con un equilibrio sovrannaturale.'
    },

    mercedes_w123: {
      id: 'mercedes_w123',
      name: 'W123 300TD Turbodiesel Wagon',
      maker: 'Mercedes-Benz',
      year: 1980,
      country: 'Germania',
      flag: '🇩🇪',
      category: 'Station Wagon Indistruttibile',
      engine: '3.0L OM617 5 Cilindri Turbodiesel',
      cylinders: 5,
      displacementCc: 2998,
      powerHp: 125,
      torqueNm: 250,
      redlineRpm: 4600,
      idleRpm: 750,
      topSpeedKmh: 170,
      weightKg: 1620,
      drivetrain: 'RWD',
      drivetrainBadge: 'RWD DIFFERENZIALE POST.',
      hasTurbo: true,
      turboBoostMaxBar: 0.8,
      isDiesel: true,
      fuelType: 'gasolio',
      fuelTankL: 72,
      fuelConsumptionRate: 0.032,
      trunkCapacityKg: 165,
      tractionBonus: 0.88,
      handling: {
        agility: 0.85,
        oversteerTendency: 0.45,
        stability: 1.1,
        brakeForce: 34.0,
        groundClearance: 0.17,
        bodyRollFactor: 0.32
      },
      dashTheme: {
        style: 'vdo_mercedes_classic',
        speedoMax: 200,
        redlineRpm: 4600,
        clusterName: 'VDO STUTTGART CLASSIC',
        dialBg: '#131518',
        tickColor: '#e2e8f0',
        needleColor: '#fb923c',
        accentColor: '#f59e0b',
        hasGlowPlug: true,
        hasTurboGauge: true
      },
      soundProfile: {
        baseFreq: 33,
        timbre: 'om617_diesel_5cyl',
        cylinders: 5,
        turboWhistle: 0.4,
        dieselKnock: 0.75
      },
      description: 'L\'apice della longevità ingegneristica tedesca: il 5 cilindri OM617 turbodiesel con pompa iniezione Bosch meccanica è capace di superare un milione di chilometri senza revisioni anche con carburanti impuri.',
      tacticalDaltonAdvice: 'Il bagagliaio immenso (165 kg) e il grande serbatoio consentono lunghissime tratte senza rifornimenti. Trazione posteriore: richiede cautela sulle salite innevate dell\'Atigun Pass.',
      tier: 2,
      unlockType: 'barn_find',
      discoveryPK: 850,
      discoveryLocation: 'Scalo Chiatte del Fiume Yukon [MP 56]',
      restorationCost: { scrap_metal: 35, engine_oil: 1, cured_timber: 2 },
      restorationStory: 'Portata in Alaska da un appaltatore della Alyeska Pipeline nel 1980. Il 5 cilindri turbodiesel OM617 da un milione di chilometri è intorpidito dal gelo; con olio fresco e puntelli in legno torna a marciare.'
    },

    mercedes_gwagen: {
      id: 'mercedes_gwagen',
      name: 'G-Klasse W460 280 GE',
      maker: 'Mercedes-Benz',
      year: 1979,
      country: 'Germania / Austria',
      flag: '🇩🇪',
      category: 'Fuoristrada Militare Longheroni',
      engine: '2.8L M110 DOHC 6 Cilindri in linea',
      cylinders: 6,
      displacementCc: 2746,
      powerHp: 156,
      torqueNm: 226,
      redlineRpm: 6000,
      idleRpm: 800,
      topSpeedKmh: 155,
      weightKg: 1980,
      drivetrain: '4WD_MANUAL',
      drivetrainBadge: '3x DIFF LOCK MECCANICO',
      hasTurbo: false,
      turboBoostMaxBar: 0,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 68,
      fuelConsumptionRate: 0.042,
      trunkCapacityKg: 150,
      tractionBonus: 1.3,
      handling: {
        agility: 0.78,
        oversteerTendency: 0.2,
        stability: 1.05,
        brakeForce: 33.0,
        groundClearance: 0.23,
        bodyRollFactor: 0.35
      },
      dashTheme: {
        style: 'vdo_mercedes_military',
        speedoMax: 200,
        redlineRpm: 6000,
        clusterName: 'VDO OFF-ROAD INSTRUMENTS',
        dialBg: '#111417',
        tickColor: '#cbd5e1',
        needleColor: '#ef4444',
        accentColor: '#3b82f6',
        hasGlowPlug: false,
        hasTurboGauge: false
      },
      soundProfile: {
        baseFreq: 36,
        timbre: 'm110_inline6',
        cylinders: 6,
        turboWhistle: 0.0,
        dieselKnock: 0.0
      },
      description: 'Sviluppato per specifiche militari con telaio a longheroni e ponti rigidi guidati da bracci longitudinali. Equipaggiato con tre blocchi meccanici al 100% per i differenziali anteriore, centrale e posteriore.',
      tacticalDaltonAdvice: 'Arrampica su pietraie franose e tronchi con disinvoltura assoluta. Il peso di quasi due tonnellate penalizza i consumi e richiede frenate anticipate nelle discese viscide.',
      tier: 3,
      unlockType: 'barn_find',
      discoveryPK: 5000,
      discoveryLocation: 'Cava Frantumatori di Atigun Pass [MP 290]',
      restorationCost: { scrap_metal: 65, electronics: 20, reinforced_coil: 1 },
      restorationStory: 'Veicolo di soccorso alpino del Dipartimento Trasporti dell\'Alaska. I tre blocchi meccanici al 100% permettono di scalare le rampe del 12% dell\'Atigun Pass non appena montata una molla rinforzata.'
    },

    defender_110: {
      id: 'defender_110',
      name: 'Defender 110 200Tdi',
      maker: 'Land Rover',
      year: 1990,
      country: 'Regno Unito',
      flag: '🇬🇧',
      category: 'Spedizione Overland Artica',
      engine: '2.5L 200Tdi Turbodiesel Iniezione Diretta',
      cylinders: 4,
      displacementCc: 2495,
      powerHp: 111,
      torqueNm: 264,
      redlineRpm: 4400,
      idleRpm: 750,
      topSpeedKmh: 130,
      weightKg: 2050,
      drivetrain: '4WD_MANUAL',
      drivetrainBadge: 'PERMANENT 4WD + DIFF-LOCK',
      hasTurbo: true,
      turboBoostMaxBar: 0.9,
      isDiesel: true,
      fuelType: 'gasolio',
      fuelTankL: 80,
      fuelConsumptionRate: 0.034,
      trunkCapacityKg: 180,
      tractionBonus: 1.32,
      handling: {
        agility: 0.72,
        oversteerTendency: 0.15,
        stability: 1.0,
        brakeForce: 32.0,
        groundClearance: 0.25,
        bodyRollFactor: 0.38
      },
      dashTheme: {
        style: 'lucas_smiths_offroad',
        speedoMax: 150,
        redlineRpm: 4500,
        clusterName: 'SMITHS EXPEDITION GAUGES',
        dialBg: '#151914',
        tickColor: '#86efac',
        needleColor: '#22c55e',
        accentColor: '#16a34a',
        hasGlowPlug: true,
        hasTurboGauge: true
      },
      soundProfile: {
        baseFreq: 31,
        timbre: 'landrover_diesel_tdi',
        cylinders: 4,
        turboWhistle: 0.45,
        dieselKnock: 0.8
      },
      description: 'Icona dell\'esplorazione globale: carrozzeria in alluminio Birmabright resistente alla ruggine, snorkel di aspirazione montato sul montante A e riduttore transfer case LT230 con blocco centrale.',
      tacticalDaltonAdvice: 'Massima capacità di carico del corridoio (180 kg) e resistenza insuperabile all\'acqua e ai guadi. Sterzo pesante e andatura lenta ma inarrestabile.',
      tier: 3,
      unlockType: 'barn_find',
      discoveryPK: 4200,
      discoveryLocation: 'Staging Depot Minatori di Wiseman [MP 265]',
      restorationCost: { scrap_metal: 60, cured_timber: 3, toolkit: 1, spare_tire: 1 },
      restorationStory: 'Veterana della Royal Geographical Society abbandonata dopo un crollo sulla pista. La carrozzeria in alluminio Birmabright non ha un filo di ruggine; 180 kg di portata e riduttore con blocco differenziale.'
    },

    volvo_245: {
      id: 'volvo_245',
      name: '245 Polar Estate B230',
      maker: 'Volvo',
      year: 1988,
      country: 'Svezia',
      flag: '🇸🇪',
      category: 'Wagon Artica di Sicurezza',
      engine: '2.3L B230 "Redblock" Iniezione LH-Jetronic',
      cylinders: 4,
      displacementCc: 2316,
      powerHp: 115,
      torqueNm: 185,
      redlineRpm: 6000,
      idleRpm: 800,
      topSpeedKmh: 175,
      weightKg: 1390,
      drivetrain: 'RWD',
      drivetrainBadge: 'RWD PONTE RIGIDO DANA 30',
      hasTurbo: false,
      turboBoostMaxBar: 0,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 60,
      fuelConsumptionRate: 0.031,
      trunkCapacityKg: 150,
      tractionBonus: 0.94,
      handling: {
        agility: 0.95,
        oversteerTendency: 0.4,
        stability: 1.2,
        brakeForce: 36.0,
        groundClearance: 0.17,
        bodyRollFactor: 0.22
      },
      dashTheme: {
        style: 'yazaki_volvo_nordic',
        speedoMax: 200,
        redlineRpm: 6000,
        clusterName: 'YAZAKI GÖTEBORG INSTRUMENTS',
        dialBg: '#12171c',
        tickColor: '#93c5fd',
        needleColor: '#38bdf8',
        accentColor: '#0284c7',
        hasGlowPlug: false,
        hasTurboGauge: false
      },
      soundProfile: {
        baseFreq: 37,
        timbre: 'volvo_redblock_4cyl',
        cylinders: 4,
        turboWhistle: 0.0,
        dieselKnock: 0.0
      },
      description: 'Il celebre "carro armato svedese" progettato per sopravvivere agli inverni scandinavi. Dotato di paraurti telescopici assorbitori, riscaldamento abitacolo ad alta efficienza e motore Redblock con tolleranze eterne.',
      tacticalDaltonAdvice: 'Eccellente stabilità su permafrost e fondo ghiacciato grazie al bilanciamento 50:50. Telaio robustissimo contro gli impatti da animali selvatici e detriti montani.',
      tier: 1,
      unlockType: 'barn_find',
      discoveryPK: 350,
      discoveryLocation: 'Miniera e Draga d\'Oro di Livengood [MP 14]',
      restorationCost: { scrap_metal: 25, spare_tire: 1 },
      restorationStory: 'Appartenuta a un geologo svedese nel 1988. Il celebre motore Redblock B230 è intatto sotto un telo incerato; servono una gomma di scorta e rottami per fissare i manicotti.'
    },

    audi_quattro: {
      id: 'audi_quattro',
      name: 'Ur-Quattro 20V Turbo',
      maker: 'Audi',
      year: 1989,
      country: 'Germania',
      flag: '🇩🇪',
      category: 'Coupé Gran Turismo Integrale',
      engine: '2.2L 5 Cilindri 20V Turbo KKK K24',
      cylinders: 5,
      displacementCc: 2226,
      powerHp: 220,
      torqueNm: 309,
      redlineRpm: 7200,
      idleRpm: 900,
      topSpeedKmh: 230,
      weightKg: 1380,
      drivetrain: 'AWD_TORSEN',
      drivetrainBadge: 'QUATTRO TORSEN + DIFF-LOCK',
      hasTurbo: true,
      turboBoostMaxBar: 1.6,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 70,
      fuelConsumptionRate: 0.046,
      trunkCapacityKg: 100,
      tractionBonus: 1.34,
      handling: {
        agility: 1.1,
        oversteerTendency: 0.2,
        stability: 1.25,
        brakeForce: 38.0,
        groundClearance: 0.15,
        bodyRollFactor: 0.18
      },
      dashTheme: {
        style: 'audi_sport_orange',
        speedoMax: 260,
        redlineRpm: 7200,
        clusterName: 'AUDI SPORT INGOLSTADT',
        dialBg: '#101014',
        tickColor: '#fb923c',
        needleColor: '#f97316',
        accentColor: '#ef4444',
        hasGlowPlug: false,
        hasTurboGauge: true
      },
      soundProfile: {
        baseFreq: 40,
        timbre: 'audi_5cyl_turbo',
        cylinders: 5,
        turboWhistle: 0.8,
        dieselKnock: 0.0
      },
      description: 'La vettura che ha rivoluzionato il motorsport introducendo la trazione integrale permanente nelle competizioni. Motore 5 cilindri turbo dal sound inconfondibile, passaruota bombati e trazione totale permanente Torsen.',
      tacticalDaltonAdvice: 'Velocità impressionante e tenuta sui curvoni del Chandalar Shelf. Richiede attenzione al sottosterzo iniziale all\'ingresso delle curve strette.',
      tier: 4,
      unlockType: 'barn_find',
      discoveryPK: 5800,
      discoveryLocation: 'Continental Divide High Camp - Valico 1.444m [MP 310]',
      restorationCost: { scrap_metal: 75, electronics: 25, cryo_coolant: 1 },
      restorationStory: 'Monumento del rallysmo Group B, collaudata dalla divisione Audi Sport sui ghiacci artici nel 1989. Il 5 cilindri 20V turbo KKK K24 è intatto; con liquido antigelo polare e rottami domina le bufere.'
    },

    bmw_e30_ix: {
      id: 'bmw_e30_ix',
      name: '325iX Touring E30',
      maker: 'BMW',
      year: 1988,
      country: 'Germania',
      flag: '🇩🇪',
      category: 'Sport Wagon Trazione Integrale',
      engine: '2.5L M20B25 6 Cilindri in linea SOHC',
      cylinders: 6,
      displacementCc: 2494,
      powerHp: 170,
      torqueNm: 222,
      redlineRpm: 6600,
      idleRpm: 850,
      topSpeedKmh: 210,
      weightKg: 1310,
      drivetrain: 'AWD_VISCOUS',
      drivetrainBadge: 'ALLRAD 37:63 VISCOUS',
      hasTurbo: false,
      turboBoostMaxBar: 0,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 55,
      fuelConsumptionRate: 0.038,
      trunkCapacityKg: 110,
      tractionBonus: 1.18,
      handling: {
        agility: 1.22,
        oversteerTendency: 0.35,
        stability: 1.15,
        brakeForce: 36.0,
        groundClearance: 0.15,
        bodyRollFactor: 0.2
      },
      dashTheme: {
        style: 'bmw_amber_classic',
        speedoMax: 240,
        redlineRpm: 6600,
        clusterName: 'BMW MOTORENWERKE MÜNCHEN',
        dialBg: '#131110',
        tickColor: '#fdba74',
        needleColor: '#ea580c',
        accentColor: '#f97316',
        hasGlowPlug: false,
        hasTurboGauge: false
      },
      soundProfile: {
        baseFreq: 38,
        timbre: 'bmw_m20_inline6',
        cylinders: 6,
        turboWhistle: 0.0,
        dieselKnock: 0.0
      },
      description: 'La prima serie 3 a quattro ruote motrici con ripartizione della coppia al 37% anteriore e 63% posteriore tramite giunto viscoso epicicloidale. Preserva l\'agilità dinamica tipica BMW su neve e fango.',
      tacticalDaltonAdvice: 'Dinamica di guida esaltante sui fondi a bassa aderenza con sovrasterzo facilmente gestibile. Il telaio touring offre un buon compromesso tra sportività e capacità di carico.',
      tier: 3,
      unlockType: 'barn_find',
      discoveryPK: 2800,
      discoveryLocation: 'Base Radar White Alice - Circolo Polare [MP 200]',
      restorationCost: { scrap_metal: 50, electronics: 18, graphene_battery: 1 },
      restorationStory: 'Utilizzata dagli ufficiali di collegamento della stazione radar durante la Guerra Fredda. La trazione Allrad viscosa 37:63 è pronta a ruggire appena collegata a un accumulatore al grafene.'
    },

    alfa_giulia: {
      id: 'alfa_giulia',
      name: 'Giulia Super 1.6 "Biscione"',
      maker: 'Alfa Romeo',
      year: 1967,
      country: 'Italia',
      flag: '🇮🇹',
      category: 'Berlina Sportiva d\'Epoca',
      engine: '1.6L Bialbero Twin-Cam 2x Weber 40 DCOE',
      cylinders: 4,
      displacementCc: 1570,
      powerHp: 112,
      torqueNm: 150,
      redlineRpm: 6800,
      idleRpm: 900,
      topSpeedKmh: 178,
      weightKg: 1020,
      drivetrain: 'RWD',
      drivetrainBadge: 'RWD BIALBERO SPORT',
      hasTurbo: false,
      turboBoostMaxBar: 0,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 46,
      fuelConsumptionRate: 0.029,
      trunkCapacityKg: 85,
      tractionBonus: 0.82,
      handling: {
        agility: 1.3,
        oversteerTendency: 0.65,
        stability: 0.9,
        brakeForce: 32.0,
        groundClearance: 0.15,
        bodyRollFactor: 0.26
      },
      dashTheme: {
        style: 'veglia_biscione_vintage',
        speedoMax: 200,
        redlineRpm: 7000,
        clusterName: 'VEGLIA BORLETTI MILANO 1967',
        dialBg: '#0e1114',
        tickColor: '#f1f5f9',
        needleColor: '#ffffff',
        accentColor: '#10b981',
        hasGlowPlug: false,
        hasTurboGauge: false
      },
      soundProfile: {
        baseFreq: 44,
        timbre: 'bialbero_carb_4cyl',
        cylinders: 4,
        turboWhistle: 0.0,
        dieselKnock: 0.0
      },
      description: '"Disegnata dal vento": carrozzeria aerodinamica a coda tronca (Kamm tail) con motore interamente in alluminio a doppio albero a camme in testa e cambio a 5 rapporti sincronizzati.',
      tacticalDaltonAdvice: 'Sensibilità di sterzo ed accelerazione brillanti grazie al peso di una tonnellata. Trazione posteriore pura con tendenza al sovrasterzo: richiede rispetto sui ponti di ghiaccio.',
      tier: 3,
      unlockType: 'barn_find',
      discoveryPK: 3500,
      discoveryLocation: 'Bivacco Cava di Sukakpak Mountain [MP 240]',
      restorationCost: { scrap_metal: 50, electronics: 15, engine_oil: 2 },
      restorationStory: 'L\'auto personale di un ingegnere italo-americano della Fluor Corp. I due carburatori Weber doppio corpo del bialbero necessitano di pulizia e olio fresco per cantare a 7.000 giri sulle serpentine montane.'
    },

    peugeot_504_dangel: {
      id: 'peugeot_504_dangel',
      name: '504 Dangel 4x4 Break',
      maker: 'Peugeot / Dangel',
      year: 1980,
      country: 'Francia',
      flag: '🇫🇷',
      category: 'Rally-Raid Safari Station Wagon',
      engine: '2.0L XN1 Inclinato a Carburatore',
      cylinders: 4,
      displacementCc: 1971,
      powerHp: 96,
      torqueNm: 160,
      redlineRpm: 5500,
      idleRpm: 800,
      topSpeedKmh: 145,
      weightKg: 1480,
      drivetrain: '4WD_MANUAL',
      drivetrainBadge: '4WD DANGEL HEAVY-DUTY',
      hasTurbo: false,
      turboBoostMaxBar: 0,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 60,
      fuelConsumptionRate: 0.033,
      trunkCapacityKg: 145,
      tractionBonus: 1.25,
      handling: {
        agility: 0.9,
        oversteerTendency: 0.2,
        stability: 1.1,
        brakeForce: 33.0,
        groundClearance: 0.22,
        bodyRollFactor: 0.32
      },
      dashTheme: {
        style: 'jaeger_french_safari',
        speedoMax: 180,
        redlineRpm: 6000,
        clusterName: 'JAEGER FRANCE OFF-ROAD',
        dialBg: '#131416',
        tickColor: '#e2e8f0',
        needleColor: '#f59e0b',
        accentColor: '#eab308',
        hasGlowPlug: false,
        hasTurboGauge: false
      },
      soundProfile: {
        baseFreq: 35,
        timbre: 'peugeot_xn1_4cyl',
        cylinders: 4,
        turboWhistle: 0.0,
        dieselKnock: 0.0
      },
      description: 'Elaborata da Henry Dangel a Sentheim: telaio rialzato di 22 cm, scatola di rinvio a due velocità con bloccaggio differenziale centrale e sospensioni a lunga escursione nate per i safari africani.',
      tacticalDaltonAdvice: 'Assorbe buche, ciottoli e solchi profondi senza alcuna fatica. Geometria eccellente per superare la pietraia dell\'Atigun Pass e le banchine dissestate dello Yukon.',
      tier: 2,
      unlockType: 'barn_find',
      discoveryPK: 2200,
      discoveryLocation: 'Stazione Idrovore Koyukuk TAPS [MP 145]',
      restorationCost: { scrap_metal: 45, waterproofing_wax: 1, toolkit: 1 },
      restorationStory: 'Ex vettura di supporto della Parigi-Dakar 1980 importata per collaudi polari estremi. La straordinaria luce a terra di 22 cm la rende invincibile sul muskeg una volta sigillati i giunti con cera.'
    },

    golf_country: {
      id: 'golf_country',
      name: 'Golf II Country Syncro',
      maker: 'Volkswagen',
      year: 1990,
      country: 'Germania / Austria',
      flag: '🇩🇪',
      category: 'Crossover Rallye Syncro',
      engine: '1.8L Digifant 8V Iniezione Elettronica',
      cylinders: 4,
      displacementCc: 1781,
      powerHp: 98,
      torqueNm: 143,
      redlineRpm: 6200,
      idleRpm: 850,
      topSpeedKmh: 162,
      weightKg: 1245,
      drivetrain: 'AWD_VISCOUS',
      drivetrainBadge: 'SYNCRO VISCOUS AWD',
      hasTurbo: false,
      turboBoostMaxBar: 0,
      isDiesel: false,
      fuelType: 'benzina',
      fuelTankL: 55,
      fuelConsumptionRate: 0.029,
      trunkCapacityKg: 105,
      tractionBonus: 1.16,
      handling: {
        agility: 1.15,
        oversteerTendency: 0.15,
        stability: 1.05,
        brakeForce: 34.0,
        groundClearance: 0.21,
        bodyRollFactor: 0.26
      },
      dashTheme: {
        style: 'vdo_golf_syncro',
        speedoMax: 220,
        redlineRpm: 6200,
        clusterName: 'VDO WOLFSBURG DIGIFANT',
        dialBg: '#0f1316',
        tickColor: '#4ade80',
        needleColor: '#22c55e',
        accentColor: '#16a34a',
        hasGlowPlug: false,
        hasTurboGauge: false
      },
      soundProfile: {
        baseFreq: 41,
        timbre: 'vw_digifant_4cyl',
        cylinders: 4,
        turboWhistle: 0.0,
        dieselKnock: 0.0
      },
      description: 'Prodotta in collaborazione con Steyr-Daimler-Puch a Graz: scocca di Golf II montata su un controtelaio tubolare con altezza da terra di 21 cm, piastre paramotore e ruota di scorta esterna basculante.',
      tacticalDaltonAdvice: 'Il giunto viscoso trasferisce istantaneamente la trazione al posteriore quando le ruote anteriori perdono aderenza sul fango o sulla fanghiglia mista a neve.',
      tier: 2,
      unlockType: 'barn_find',
      discoveryPK: 1500,
      discoveryLocation: 'Officina Camionisti di Coldfoot Camp [MP 115]',
      restorationCost: { scrap_metal: 40, electronics: 12, spare_tire: 1 },
      restorationStory: 'Acquistata da un pilota di bush-plane austriaco per raggiungere le piste isolate. Il telaio tubolare rialzato Syncro è in condizioni impeccabili; bastano pochi cablaggi e una gomma nuova.'
    }
  },

  // Vehicle Parameters (Dynamic default mapped to default vehicle)
  VEHICLE: {
    ACCELERATION: 18.0,
    BRAKE_FORCE: 32.0,
    MAX_SPEED_KMH: 140,
    REVERSE_MAX_SPEED: 35,
    TURN_SPEED: 2.2,
    DRIFT_RECOVERY: 4.5,
    FUEL_CONSUMPTION_RATE: 0.035, // L/sec at full throttle
    IDLE_FUEL_RATE: 0.005,
    OVERHEAT_RATE: 0.08,
    COOLING_RATE: 0.05,
    BATTERY_DRAIN_LIGHTS: 0.02,
    BATTERY_CHARGE_RATE: 0.04,
  },

  // Player On Foot
  PLAYER_FOOT: {
    WALK_SPEED: 4.5,
    SPRINT_SPEED: 8.5,
    STAMINA_DRAIN: 15.0,
    STAMINA_RECOVERY: 20.0,
    INTERACT_RADIUS: 4.0,
  },

  // Survival baseline
  SURVIVAL: {
    MAX_HEALTH: 100,
    MAX_STAMINA: 100,
    MAX_HUNGER: 100,
    MAX_THIRST: 100,
    MAX_HEAT: 100,
    HUNGER_RATE: 0.04,   // per sec
    THIRST_RATE: 0.08,
    FREEZING_TEMP_DAMAGE: 1.5,
    TOXIC_DAMAGE: 2.0,
  },

  // Points of Interest (POIs) - Structured by real-world Dalton Highway infrastructure
  POI_TYPES: {
    SETTLEMENT_HUB: {
      name: 'Insediamento e Truck Stop Storico',
      icon: '🏘️',
      isSettlement: true,
      lootTable: [], // Trade hub, not simple scavenge
      dangerLevel: 0.05
    },
    REFINERY_DEPOT: {
      name: 'Parco Serbatoi Gasolio Artico di Livengood',
      icon: '🛢️',
      biomeId: 'rusty_periphery',
      lootTable: ['refined_fuel', 'engine_oil', 'scrap_metal', 'fuel_canister'],
      dangerLevel: 0.25,
      loreNote: 'Deposito carburante invernale ad alto cetano della vecchia miniera di Livengood. I manometri indicano riserve di gasolio liquido intatte.'
    },
    FORESTRY_LUMBER_YARD: {
      name: 'Piazzale Taglio Picea Nera dello Yukon',
      icon: '🪓',
      biomeId: 'black_pine_woods',
      lootTable: ['cured_timber', 'antiseptic_resin', 'first_aid_bandage', 'toolkit'],
      dangerLevel: 0.2,
      loreNote: 'Accatastamento di tronchi di picea nera e fusti di resina idrofobica pronti per le chiatte fluviali pre-collasso.'
    },
    HYDRO_PUMP_STATION: {
      name: 'Impianto Idrovore e Valvole Koyukuk TAPS',
      icon: '💧',
      biomeId: 'flooded_marshland',
      lootTable: ['peat_filter', 'waterproofing_wax', 'water_purified', 'spare_tire'],
      dangerLevel: 0.35,
      loreNote: 'Quadro valvole parzialmente allagato dal disgelo del muskeg. I filtri a membrana di torba sono ancora intatti nei cestelli di decantazione.'
    },
    IONIC_RADAR_ARRAY: {
      name: 'Parabola Radar Troposferica White Alice (DEW Line)',
      icon: '📡',
      biomeId: 'glass_crater',
      lootTable: ['graphene_battery', 'rad_shield_plate', 'electronics', 'ammo_flare'],
      dangerLevel: 0.5,
      loreNote: 'Gruppo di continuità militare del sistema di difesa aerea della Guerra Fredda. I condensatori al grafene mantengono ancora carica statica.'
    },
    QUARRY_CRUSHER_SITE: {
      name: 'Cava Frantumatori di Ardesia DOT Atigun Pass',
      icon: '⚙️',
      biomeId: 'iron_gorge',
      lootTable: ['reinforced_coil', 'tungsten_drill_bit', 'armor_plate', 'scrap_metal'],
      dangerLevel: 0.4,
      loreNote: 'Impianto di frantumazione ghiaia per la manutenzione del valico montano. Si possono recuperare balestre pesanti e inserti al tungsteno.'
    },
    POLAR_METAR_SHELTER: {
      name: 'Capsula Rifugio Spazzaneve Arctic Cat',
      icon: '🏕️',
      biomeId: 'permafrost_highlands',
      lootTable: ['cryo_coolant', 'thermal_lining', 'toolkit', 'water_purified'],
      dangerLevel: 0.3,
      loreNote: 'Bivacco coibentato dell\'Alaska DOT per gli operatori delle frese polari. Nelle stive ci sono scorte di fluido antigelo a -55°C.'
    },
    OVERTURNED_CONVOY: {
      name: 'Autocisterna Kenworth Artica Ribaltata',
      icon: '🚛',
      lootTable: ['fuel_canister', 'spare_tire', 'toolkit', 'scrap_metal'],
      dangerLevel: 0.4,
      loreNote: 'Il semirimorchio a tre assi è scivolato nel canalone laterale durante una bufera. C\'è ancora gasolio pesante nel serbatoio coibentato.'
    },
    MILITARY_CHECKPOINT: {
      name: 'Posto di Blocco Alaska State Troopers',
      icon: '🚧',
      lootTable: ['ammo_flare', 'armor_plate', 'medkit', 'canned_stew'],
      dangerLevel: 0.45,
      loreNote: 'Garitta blindata di controllo transito con barriere d\'acciaio per il blocco della Haul Road. Cassette mediche di emergenza stivate all\'interno.'
    }
  },

  // Modular Engineering Upgrades (4 Branches: Chassis, Powertrain, Armor, Avionics)
  UPGRADES: {
    // 1. ASSETTO & TRAZIONE (Chassis & Grip)
    STUDDED_TIRES: {
      id: 'studded_tires',
      category: 'chassis',
      categoryName: 'Assetto & Trazione',
      icon: '🛞',
      name: 'Pneumatici Chiodati Nokian Hakkapeliitta',
      cost: { scrap_metal: 25, spare_tire: 1 },
      desc: '+35% aderenza su ghiaccio e permafrost; riduce del 25% la distanza di arresto su fondo scivoloso.',
      statLabel: '+35% Grip Ghiaccio & Neve'
    },
    RALLY_SUSPENSION: {
      id: 'rally_suspension',
      category: 'chassis',
      categoryName: 'Assetto & Trazione',
      icon: '🌀',
      name: 'Assetto Rialzato Bilstein & Molle Heavy-Duty',
      cost: { scrap_metal: 35, toolkit: 1 },
      desc: '+5 cm luce libera a terra; assorbe il 65% dei danni da buche e dossi ed elimina l\'affossamento sulla ghiaia.',
      statLabel: '+5cm Luce / -65% Danni Buche'
    },
    DIFF_LOCK_LSD: {
      id: 'diff_lock_lsd',
      category: 'chassis',
      categoryName: 'Assetto & Trazione',
      icon: '⚙️',
      name: 'Differenziale Autobloccante Meccanico LSD',
      cost: { scrap_metal: 45, electronics: 15, engine_oil: 1 },
      desc: 'Elimina lo slittamento della ruota scarica sui fondi misti asfalto/neve/fango; +20% spinta e tenuta in accelerazione.',
      statLabel: '+20% Trazione Coppia Mista'
    },

    // 2. MOTORE & TERMO (Powertrain & Cold Weather)
    BLOCK_HEATER: {
      id: 'block_heater',
      category: 'engine',
      categoryName: 'Motore & Termo',
      icon: '🔥',
      name: 'Preriscaldatore Ausiliario Webasto Polare',
      cost: { scrap_metal: 30, fuel_canister: 1, electronics: 10 },
      desc: 'Mantiene il blocco motore a 45°C anche a -40°C esterni; azzera l\'usura delle partenze a freddo e il consumo batteria.',
      statLabel: 'Partenza Istantanea a -40°C'
    },
    COPPER_RADIATOR: {
      id: 'copper_radiator',
      category: 'engine',
      categoryName: 'Motore & Termo',
      icon: '❄️',
      name: 'Radiatore Maggiorato in Rame a 3 Fila',
      cost: { scrap_metal: 35, engine_oil: 1 },
      desc: 'Dimezza il surriscaldamento sotto sforzo continuo; impedisce il congelamento del liquido antigelo nei valichi montani.',
      statLabel: 'Raffreddamento Rame Stabile 80°C'
    },
    TURBO_BOOST_KIT: {
      id: 'turbo_boost_kit',
      category: 'engine',
      categoryName: 'Motore & Termo',
      icon: '💨',
      name: 'Kit Intercooler & Wastegate da Gara',
      cost: { scrap_metal: 50, electronics: 20 },
      desc: '+0.35 Bar di pressione di sovralimentazione massima (+18% spinta e accelerazione); scarico pop-off e fischio turbo amplificati.',
      statLabel: '+0.35 Bar Boost Turbo & +18% Spinta'
    },
    SNORKEL_INTAKE: {
      id: 'snorkel_intake',
      category: 'engine',
      categoryName: 'Motore & Termo',
      icon: '🤿',
      name: 'Snorkel con Prefiltro Polveri Ciclonico',
      cost: { scrap_metal: 25, toolkit: 1 },
      desc: 'Aspirazione alta sul montante del tetto: consente di guadare acquitrini e fiumi allagati proteggendo il motore da fango e sabbia.',
      statLabel: 'Guado Acqua & Protezione Filtri'
    },

    // 3. TELAIO & AUTONOMIA (Armor & Range)
    SKID_PLATE: {
      id: 'skid_plate',
      category: 'armor',
      categoryName: 'Telaio & Autonomia',
      icon: '🛡️',
      name: 'Slitta Paracoppa in Duralluminio Forgiato',
      cost: { scrap_metal: 35, armor_plate: 1 },
      desc: 'Protegge coppa dell\'olio, campana frizione e scarico; dimezza i danni da impatto con sassi, massi caduti e cunette.',
      statLabel: '-50% Danno da Pietrisco & Massi'
    },
    HEAVY_BULLBAR: {
      id: 'heavy_bullbar',
      category: 'armor',
      categoryName: 'Telaio & Autonomia',
      icon: '🦬',
      name: 'Rostro Frontale Corazzato Spingitutto',
      cost: { scrap_metal: 45, toolkit: 1 },
      desc: 'Riduce del 70% i danni da impatto frontale; demolisce fusti di cantiere e tronchi leggeri senza arrestare la marcia.',
      statLabel: '-70% Danno Frontale / Spinta Ostacoli'
    },
    AUX_FUEL_CELL: {
      id: 'aux_fuel_cell',
      category: 'armor',
      categoryName: 'Telaio & Autonomia',
      icon: '⛽',
      name: 'Serbatoio Ausiliario Coibentato (+40L)',
      cost: { scrap_metal: 40, fuel_canister: 2 },
      desc: 'Aggiunge un serbatoio ausiliario blindato da 40 litri, raddoppiando l\'autonomia nei lunghi tratti deserti della Haul Road.',
      statLabel: '+40 Litri Serbatoio Carburante'
    },
    ROOF_CARGO_RACK: {
      id: 'roof_cargo_rack',
      category: 'armor',
      categoryName: 'Telaio & Autonomia',
      icon: '📦',
      name: 'Portapacchi da Tetto Expedition Heavy-Duty',
      cost: { scrap_metal: 30, cured_timber: 2 },
      desc: 'Struttura tubolare aerodinamica sul padiglione: aumenta la portata massima di carico del bagagliaio di +45 kg su qualsiasi vettura.',
      statLabel: '+45 kg Capacità Bagagliaio'
    },

    // 4. AVIONICA & VISIONE (Avionics & Optics)
    RALLY_LIGHT_BAR: {
      id: 'rally_light_bar',
      category: 'avionics',
      categoryName: 'Avionica & Visione',
      icon: '💡',
      name: 'Barra 4 Fari di Profondità Hella Rally 2000',
      cost: { scrap_metal: 30, electronics: 20 },
      desc: 'Raddoppia la gittata dei fari fino a 70 metri con fascio allargato; fende la nebbia fitta, le bufere di neve e la notte polare.',
      statLabel: 'Gittata Fari 70m Fascio Largo'
    },
    CB_RADAR_SCANNER: {
      id: 'cb_radar_scanner',
      category: 'avionics',
      categoryName: 'Avionica & Visione',
      icon: '📡',
      name: 'Radio CB Dalton Convoy & Georadar Ostacoli',
      cost: { scrap_metal: 35, electronics: 25 },
      desc: 'Scansiona la carreggiata e notifica con segnale acustico e allarme visivo sulla plancia gli ostacoli e le buche con 120m di anticipo.',
      statLabel: 'Radar Ostacoli & Allarme CB 120m'
    },
    AGM_DUAL_BATTERY: {
      id: 'agm_dual_battery',
      category: 'avionics',
      categoryName: 'Avionica & Visione',
      icon: '🔋',
      name: 'Doppia Batteria AGM al Gel Deep-Cycle',
      cost: { scrap_metal: 25, electronics: 15 },
      desc: 'Capacità elettrica raddoppiata e ricarica ultra-rapida; immunità totale ai cali di tensione e blackout delle tempeste ioniche.',
      statLabel: 'Immunità Elettrica & 2x Ricarica'
    },

    // Backwards compatibility aliases
    BULLBAR: { id: 'heavy_bullbar', name: 'Rostro Frontale Corazzato', cost: { scrap_metal: 45, toolkit: 1 }, desc: 'Riduce del 70% i danni frontali al veicolo e demolisce ostacoli leggeri.', statLabel: '-70% Danno Frontale' },
    ROOF_LIGHTS: { id: 'rally_light_bar', name: 'Barra Fari Ausiliari a LED', cost: { scrap_metal: 30, electronics: 20 }, desc: 'Raddoppia il raggio e l\'ampiezza del fascio luminoso nella nebbia.', statLabel: 'Gittata Fari 70m' },
    OFFROAD_TIRES: { id: 'studded_tires', name: 'Pneumatici Chiodati M+S', cost: { scrap_metal: 25, spare_tire: 1 }, desc: 'Aumenta la trazione su fango (+40%) e ghiaccio (+70%).', statLabel: '+35% Grip Ghiaccio' },
    AUX_TANK: { id: 'aux_fuel_cell', name: 'Serbatoio Ausiliario Blindato', cost: { scrap_metal: 40, fuel_canister: 2 }, desc: 'Aumenta la capienza del carburante da 50L a 90L.', statLabel: '+40L Serbatoio' },
    TURBO_COOLER: { id: 'copper_radiator', name: 'Radiatore Maggiorato ad Aria', cost: { scrap_metal: 35, engine_oil: 1 }, desc: 'Dimezza il surriscaldamento del motore a velocità sostenute.', statLabel: 'Raffreddamento Rame' },
    ARMORED_HULL: { id: 'skid_plate', name: 'Pannelli di Blindatura Composita', cost: { scrap_metal: 35, armor_plate: 1 }, desc: 'Aumenta l\'integrità strutturale del veicolo del 50%.', statLabel: '-50% Danno Sassi' }
  }
};
